<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>2013 BCA CAMPAIGN: INTERNATIONAL TERMS & CONDITIONS</h2>
		<h3>Effective Date:  August 1, 2013</h3>

		<p><strong>Welcome to The Estée Lauder Companies’ Breast Cancer Awareness Campaign Facebook Application (the <i>"Application"</i>).</strong></p>
		<p>The Estée Lauder Companies Inc. provides the content and services available on the Application to you subject to the following terms and conditions, our Privacy Policy and other terms and conditions and policies which you may find throughout our Application in connection with certain functionality, features or promotions as well as customer service, all of which are deemed a part of and included within these terms and conditions (collectively, <i>"Terms and Conditions"</i>). By accessing or using the Application, you are acknowledging that you have read, understand, and agree, without limitation or qualification, to be bound by these Terms and Conditions.</p>

		<h3>1. Privacy</h3>
		<p>Please review our <strong>Privacy Policy</strong> so that you may understand our privacy practices.</p>

		<h3>2. Intellectual Property</h3>
		<p>Except from any information and/or content that is provided by Facebook, Inc. with respect to use of its platform, all information and content otherwise available on the Application and its “look and feel”, including but not limited to trademarks, logos, service marks, text, graphics, logos, button icons, images, audio clips, data compilations and software, and the compilation and organization thereof (collectively, the <stong><i>"Content"</i></strong>) is the property of The Estée Lauder Companies Inc., our affiliates, partners or licensors, and is protected by United States and international laws, including laws governing copyrights and trademarks.</p>
		<p>Except as set forth in the limited licenses in <strong>Section 3</strong>, or as required under applicable law, neither the Content nor any portion of the Application may be used, reproduced, duplicated, copied, sold, resold, accessed, modified, or otherwise exploited, in whole or in part, for any purpose without our express, prior written consent.</p>

		<h3>3. Limited Licenses</h3>
		<p>We grant you a limited, revocable, and non-exclusive license to access and make personal use of the Application. This limited license does not include the right to: (a) frame or utilize framing techniques to enclose the Application or any portion thereof; (b) republish, redistribute, transmit, sell, license or download the Application or any and/or all Content (except caching or as necessary to view the Application); (c) make any use of the Application or any and/or all Content other than personal use; (d) modify, reverse engineer or create any derivative works based upon either the Application or any and/or all Content; (e) collect account information for the benefit of yourself or another party; (f) use any meta tags or any other "hidden text" utilizing any and/or all Content; or (g) use software robots, spiders, crawlers, or similar data gathering and extraction tools, or take any other action that may impose an unreasonable burden or load on our infrastructure.  You must retain, without modification, all proprietary notices on the Application or affixed to or contained in the Application.</p>
		<p>Any unauthorized use by you of the Application or any and/or all of our Content automatically terminates the limited licenses set forth in this <strong>Section 3</strong> without prejudice to any other remedy provided by applicable law or these Terms and Conditions.</p>

		<h3>4. Your Obligations and Responsibilities</h4>
		<p>In the access or use of the Application, you shall comply with these Terms and Conditions and the special warnings or instructions for access or use posted on the Application. You shall act always in accordance with the law, custom and in good faith. You may not make any change or alteration to the Application or any Content or services that may appear on this Application and may not impair in any way the integrity or operation of the Application. Without limiting the generality of any other provision of these Terms and Conditions, if you default negligently or willfully in any of the obligations set forth in these Terms and Conditions, you shall be liable for all the losses and damages that this may cause to The Estée Lauder Companies, our affiliates, partners or licensors.</p>

		<h3>5. Third Party Links</h3>
		<p>We are not responsible for the content of any off-website pages or any other websites linked to or from the Application. Links appearing on the Application are for convenience only and are not an endorsement by us, our affiliates or our partners of the referenced content, product, service, or supplier. Your linking to or from any off-website pages or other websites is at your own risk. We are in no way responsible for examining or evaluating, and we do not warrant the offerings of, off-website pages or any other websites linked to or from the Application, nor do we assume any responsibility or liability for the actions, content, products, or services of such pages and websites, including, without limitation, their privacy policies and terms and conditions. You should carefully review the terms and conditions and privacy policies of all off-website pages and other websites that you visit.</p>

		<h3>6. User Content</h3>
		<p>When you transmit, upload, post, e-mail or otherwise make available data, text, software, music, sound, photographs, graphics, images, videos, messages or other materials (<strong><i>"User Content")</i></strong> on the Application, you are entirely responsible for such User Content.  It is our policy to decline unsolicited suggestions and ideas. Notwithstanding our policy with regard to unsolicited suggestions and ideas, any inquiries, feedback, suggestions, ideas or other information you provide us (collectively, <strong><i>"Submissions"</i></strong>) will be treated as non-proprietary and non-confidential. You also acknowledge that your Submission will not be returned and we may use your Submission, and any ideas, concepts or know how contained therein, without payment of money or any other form of consideration, for any purpose including, without limitation, developing, manufacturing, distributing and marketing products.  Submissions shall be treated as User Content.</p>
		<p>Subject to the terms of our <strong>Privacy Policy</strong>, by transmitting or posting any User Content, you hereby grant us a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to copy, use, reproduce, modify, adapt, translate, publish, license, distribute, sell or assign the User Content in any way as we see fit, including but not limited to copying in whole or in part, creating derivative works from, distributing and displaying any User Content in any form, media, or technology, whether now known or hereafter developed, alone or as part of other works, or using the User Content within or in connection with our products or services.  In addition, you hereby grant us the right to use your name, image, and likeness for any purpose in any way that we see fit with your User Content.</p>
		<p>All third parties, and not we, are entirely responsible for all User Content that they post to the Application.  You agree not to engage in or assist or encourage others to engage in transmitting, uploading, posting, e-mailing or otherwise making available on the Application User Content that that (a) is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, pornographic, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable; (b) you do not have a right to make available under any law or under contractual or fiduciary relationships; (c)<u> is known by you to be  false, inaccurate or misleading; (d) you were compensated for or granted any consideration by any third party; or </u>(e) infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party.  In addition, you agree not to transmit, upload, post, e-mail, or otherwise make available any software viruses, unsolicited or unauthorized advertising, solicitation or promotional material, including chain letters, mass mailings, or any form of "spam."  You further agree not to (i) impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with any person or entity; (ii) "stalk" or otherwise harass <u>including advocating harassment of another</u>, entrap or harm any third party <u>including harming minors in any way</u>; (iii) forge headers or otherwise manipulate identifiers in order to disguise the origin of any User Content; (iv) intentionally or unintentionally violate any applicable local, state, national or international law; or (v) collect or store personally identifiable data about other users.</p>
		<p>We do not endorse or control the User Content transmitted or posted on the Application and therefore, we do not guarantee the accuracy, integrity or quality of User Content.  You understand that by using the Application, you may be exposed to User Content that is offensive, indecent or objectionable to you. Under no circumstances will we be liable in any way for any User Content, including, without limitation, for any errors or omissions in any User Content, or for any loss or damage of any kind incurred by you as a result of the use of any User Content transmitted, uploaded, posted, e-mailed or otherwise made available via the Application.</p>

		<p>We are in no way responsible for examining or evaluating the Action in which you and your Circle of Strength have agreed to engage, nor are we obligated to endorse your Action or Circle of Strength.   We do not assume any responsibility or liability for the selection or completion of your Action or for the failure to complete the Action by you or any one in your Circle of Strength.<br/>
		You acknowledge that we have the right (but not the obligation) in our sole discretion to refuse to post or remove any User Content <u>and we reserve the right to change, condense, or delete any User Content</u>. Without limiting the generality of the foregoing or any other provision of these Terms and Conditions, we have the right to remove any User Content that violates these Terms and Conditions or is otherwise objectionable and we reserve the right to refuse service without prior notice for any users who violate these Terms and Conditions or infringe the rights of others.</p>

		<h3>7. Copyright Complaints</h3>
		<p>We respect the intellectual property of others. If you believe that copyrighted materials have been copied in a way that constitutes copyright infringement, please send an e-mail or written notice to our Designated Agent for notices of infringement and provide the following: (i) identification of the copyrighted work(s) that you claim has been infringed and confirmation that you are the copyright owner or authorized to act on the copyright owner's behalf; (ii) a description of the material that you claim is infringing and the location of that material on the Site; (iii) your address, telephone number and email address.</p>
		<p><strong>Our Designated Agent for notice for claims of copyright infringement is Gregg Marrazzo, Senior Vice President and Deputy General Counsel, The Estée Lauder Companies Inc., 767 Fifth Avenue, New York, N.Y.  10153.  Telephone: (212) 277-2320.  Email: gmarrazz@estee.com.</strong></p>
		<p>NOTE: THE ABOVE CONTACT INFORMATION IS PROVIDED EXCLUSIVELY FOR NOTIFYING AVEDA THAT COPYRIGHTED MATERIAL MAY HAVE BEEN INFRINGED.  ALL OTHER INQUIRIES WILL NOT RECEIVE A RESPONSE THROUGH THIS PROCESS AND SHOULD BE DIRECTED TO OUR CUSTOMER SERVICE GROUP BY EMAIL TO consumercare-us@gcc.elc.estee.com.</p>

		<h3>8. Representations and Warranties; Limitation of Liability</h3>
		<p>THE APPLICATION IS PRESENTED "AS IS." WE MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, IN CONNECTION WITH THESE TERMS AND CONDITIONS OR THE APPLICATION, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE, EXCEPT TO THE EXTENT SUCH REPRESENTATIONS AND WARRANTIES ARE NOT LEGALLY EXCLUDABLE.</p>
		<p>YOU AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, WE WILL NOT BE RESPONSIBLE OR LIABLE (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE), UNDER ANY CIRCUMSTANCES, FOR ANY (a) INTERRUPTION OF BUSINESS; (b) ACCESS DELAYS OR ACCESS INTERRUPTIONS TO THE APPLICATION; (c) DATA NON-DELIVERY, MISDELIVERY, CORRUPTION, DESTRUCTION OR OTHER MODIFICATION; (d) LOSS OR DAMAGES OF ANY SORT INCURRED AS A RESULT OF DEALINGS WITH OR THE PRESENCE OF OFF-WEBAPPLICATION LINKS ON THE APPLICATION; (e) COMPUTER VIRUSES, SYSTEM FAILURES OR MALFUNCTIONS WHICH MAY OCCUR IN CONNECTION WITH YOUR USE OF THE APPLICATION, INCLUDING DURING HYPERLINK TO OR FROM THIRD PARTY WEBAPPLICATIONS (f) ANY INACCURACIES OR OMISSIONS IN CONTENT OR (g) EVENTS BEYOND OUR REASONABLE CONTROL.</p>
		<p>FURTHER, TO THE FULLEST EXTENT PERMITTED BY LAW, WE WILL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND (INCLUDING LOST PROFITS) RELATED TO THE APPLICATION OR YOUR USE THEREOF REGARDLESS OF THE FORM OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND IN NO EVENT SHALL OUR MAXIMUM AGGREGATE LIABILITY EXCEED ONE HUNDRED DOLLARS ($100.00).</p>
		<p>YOU AGREE THAT NO CLAIMS OR ACTION ARISING OUT OF, OR RELATED TO, THE USE OF THE APPLICATION OR THESE TERMS AND CONDITIONS MAY BE BROUGHT BY YOU MORE THAN ONE (1) YEAR AFTER THE CAUSE OF ACTION RELATING TO SUCH CLAIM OR ACTION AROSE.</p>

		<h3>9. Indemnification</h3>
		<p>You agree to defend, indemnify and hold us harmless for any loss, damages or costs, including reasonable attorneys' fees, resulting from any third party claim, action, or demand resulting from your use of the Application or breach of these Terms and Conditions. You also agree to indemnify us for any loss, damages, or costs, including reasonable attorneys' fees, resulting from your use of software robots, spiders, crawlers, or similar data gathering and extraction tools, or any other action you take that imposes an unreasonable burden or load on our infrastructure.</p>

		<h3>10. Disputes</h3>
		<p>With respect to any dispute regarding the Application, all rights and obligations and all actions contemplated by these Terms and Conditions shall be governed by the laws of New York, as if the Terms and Conditions were a contract wholly entered into and wholly performed within New York. Any dispute relating in any way to your visit to the Application shall be submitted to confidential arbitration in New York and you submit to the jurisdiction and proceedings thereof, except that, to the extent you have in any manner violated or threatened to violate our intellectual property rights or the intellectual property rights of our affiliates, partners or licensors or otherwise have a cause of action in equity, we may seek injunctive or other appropriate relief in any court of competent jurisdiction and you consent to jurisdiction and venue in any such court for such purposes.  Arbitration under this agreement shall be conducted under the Consumer-Related Disputes Supplementary Rules then prevailing with the American Arbitration Association. The arbitrator's award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under these Terms and Conditions shall be joined to an arbitration involving any other party subject to this Terms and Conditions, whether through class arbitration proceedings or otherwise.</p>

		<h3>11. General</h3>
		<p>You acknowledge and agree that these Terms and Conditions constitute the complete and exclusive agreement between us concerning your use of the Application, and supersede and govern all prior proposals, agreements, or other communications.</p>
		<p>We reserve the right, in our sole discretion, to change these Terms and Conditions at any time by posting the changes on the Application and providing notice of such change. Any changes are effective immediately upon posting to the Application and release of notice of such change. Your continued use of the Application thereafter constitutes your agreement to all such changed Terms and Conditions. We may, with or without prior notice, terminate any of the rights granted by these Terms and Conditions. You shall comply immediately with any termination or other notice, including, as applicable, by ceasing all use of the Application.</p>
		<p>Nothing contained in these Terms and Conditions shall be construed as creating any agency, partnership, or other form of joint enterprise between us. Our failure to require your performance of any provision hereof shall not affect our full right to require such performance at any time thereafter, nor shall our waiver of a breach of any provision hereof be taken or held to be a waiver of the provision itself. In the event that any provision of these Terms and Conditions shall be unenforceable or invalid under any applicable law or be so held by any applicable arbitral award or court decision, such unenforceability or invalidity shall not render these Terms and Conditions unenforceable or invalid as a whole but these Terms and Conditions shall be modified, to the extent possible, by the adjudicating entity to most fully reflect the original intent of the parties as reflected in the original provision.</p>
		<p>If you have any questions regarding these Terms and Conditions, please email us at consumercare-us@gcc.elc.estee.com.</p>

	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>