<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>CAMPAÑA BCA 2013: TERMINOS Y CONDICIONES INTERNACIONALES</h2>
		<h3>Fecha Efectiva: 1 de Agosto de 2013</h3>

		<p><strong>Bienvenidos a The Estée Lauder Companies' Breast Cancer Awareness Campaign Aplicación en Facebook (<i>"La Aplicación</i>).</strong></p>
		<p>The Estée Lauder Companies Inc. ofrece los contenidos y servicios disponibles en la aplicación sujetos a los siguientes términos y condiciones, nuestra política de privacidad y otros términos, condiciones y políticas que usted puede encontrar a través de nuestra aplicación en relación con determinadas funciones, características o promociones, así como servicio al cliente, los cuales están incluidos en estos términos y condiciones (en adelante, <stong><i>"Términos y Condiciones"</i></strong>). Al accesar o utilizar esta aplicación, usted reconoce que ha leído, entendido y acepta, sin limitación o calificación, estar obligado a estos Términos y Condiciones.</p>

		<h3>1. Privacidad</h3>
		<p>Por favor revise nuestra <strong>Política de Privacidad</strong> para que usted pueda entender nuestras prácticas de privacidad.</p>

		<h3>2. Propiedad Intelectual</h3>
		<p>A excepción de cualquier información y/o contenido que sea proporcionado por Facebook Inc. con respecto al uso de su plataforma, toda información y contenido disponible de otra manera en la aplicación y su "look and feel" incluyendo pero no limitando a :  Marcas comerciales, logotipos, marcas, textos, gráficos, iconos, imágenes, clips de audio, compilaciones de datos y software, y la recopilación de los mismos (en adelante, el <i><strong>"Contenido"</strong></i>) es propiedad de The Estée Lauder Companies Inc., nuestros afiliados, socios o licenciantes, y está protegido por las leyes estadounidenses e internacionales, incluidas las leyes que rigen los derechos de autor y marcas registradas.</p>
		<p>Salvo lo dispuesto en la Sección 3, o según se requiera bajo ley aplicable, ni el Contenido ni ninguna parte de la Aplicación podrá ser usada para reproducir, duplicar, copiar, vender, revender, acceder, modificar, en su totalidad o en parte para cualquier uso sin nuestro consentimiento previo y por escrito.</p>

		<h3>3. Licencias Limitadas</h3>
		<p>Le otorgamos una licencia limitada, revocable, y no exclusiva para acceder y hacer uso personal de la solicitud. Esta licencia limitada no incluye el derecho de: (a) enmarcar o utilizar técnicas de enmarcado para cualquier parte de la Aplicación o cualquier parte de la misma; (b) publicar, distribuir, transmitir, vender, licenciar, o descargar la aplicación o y/o todo el contenido (excepto por el almacenamiento en caché o si es necesario para ver la aplicación; (c) hacer cualquier uso de la Aplicación de cualquier y/o todo del contenido que no sea para uso personal; (d) modificar, aplicar ingeniería inversa o crear ningún trabajo derivado basado en la Aplicación de cualquier y/o todos los contenidos; (e) recoger información de la cuenta para el beneficio de sí mismo o de un tercero; (f) utilizar cualquier META TAG o cualquier otro "HIDDEN TEXT" utilizando cualquier y/o todos los contenidos; (g) utilizar SOFTWARE ROBOTS, arañas, rastreadores, o similares de recopilación y herramientas de extracción, o tomar cualquier otra acción que pueda imponer una carga irracional en nuestra infraestructura. Usted debe conservar sin excepciones, todos los avisos de propiedad de la Aplicación, adjuntos o contenidos en la Aplicación.</p>
		<p>Cualquier uso no autorizado por usted de la Aplicación o de cualquier y/o todo Contenido automáticamente revocará las l icencias limitadas establecidas en la Sección 3 y sin perjuicio de cualquier otro recurso previsto por la ley aplicable o estos Términos y Condiciones.</p>

		<h3>4. Sus obligaciones y responsabilidades</h4>
		<p>En el acceso o el uso de la Aplicación, usted deberá cumplir con estos Términos y Condiciones y las advertencias especiales o instrucciones para el acceso o el uso de la Aplicación. Usted deberá actuar siempre de acuerdo con la ley, la costumbre y buena fe. Usted no puede hacer ningún cambio o alteración a la Aplicación  o a cualquier contenido o servicios que pudieran aparecer en esta Aplicación y no se puede alterar de ningún modo alguno la integridad o el funcionamiento de la Aplicación. Sin limitar la generalidad o cualquier otra disposición de estos Términos y Condiciones, en caso de incumplimiento por negligencia o intencionalmente de cualquiera de las obligaciones establecidas en estos Términos y Condiciones, usted será responsable por todas las pérdidas y daños que puedan causar a The Estée Lauder Companies, nuestros socios, afiliados o licenciantes.</p>

		<h3>5. Enlances con Terceros</h3>
		<p>No nos hacemos responsables por el contenido de cualquier página fuera del sitio web o de otros sitios web vinculados hacia o desde la Aplicación. Los enlaces que aparecen en la Aplicación son sólo para conveniencia y no constituyen una aprobación por parte de nosotros, nuestros afiliados o nuestros socios de las referencias a contenido, producto, servicio o proveedor. Su conexión hacia o desde cualquier página fuera del sitio web u otros sitios web es bajo su propio riesgo. No somos de ninguna manera responsables de examinar, evaluar y no garantizamos las ofertas de páginas externas al Sitio Web o de cualquier otro sitio web vinculados hacia o desde la Aplicación, ni asumimos ninguna responsabilidad por las acciones, contenido, productos o servicios de dichas páginas y sitios web incluidos, entre otros sus Políticas de Privacidad y Términos y Condiciones. Usted debe revisar cuidadosamente los términos y condiciones así como las políticas de privacidad de todas las páginas fuera del sitio web y otros sitios web que usted visite.</p>

		<h3>6. Contenido del Usuario</h3>
		<p>Al transmitir, publicar, enviar por correo electrónico o de cualquier otra manera hace disponer de datos, textos, software, música, sonido, fotografías, gráficos, imágenes, vídeos, mensajes o cualquier otro material (<i><strong>"Contenido del Usuario"</strong></i>)  de la Aplicación, usted es completamente responsable de dicho Contenido del Usuario. Es nuestra política declinar ideas o sugerencias no solicitadas. A pesar de nuestra política con respecto a las sugerencias e ideas no solicitadas, cualquier consulta, comentarios, sugerencias, ideas o cualquier otra información que nos proporcionan (en adelante, <i><strong>"Comentarios"</strong></i>) serán tratados como no propietario y no confidencial. Usted también reconoce que su Comentario no será devuelto y podemos usar su Comentario y cualquier idea, concepto o Know How contenida ahí mismo, sin el pago de dinero o cualquier otro tipo de consideración, para cualquier propósito, incluyendo sin limitación, desarrollo, fabricación distribución, y comercialización de productos. Sus Comentarios serán tratados como Contenido de Usuario.</p>
		<p>Sujeto a los términos de nuestra <strong>Política de Privacidad</strong>, al transmitir o publicar cualquier Contenido de Usuario, nos da autorización para utilizar de manera transferible, sin exclusividad y sin sub licenciamiento libre de cualquier regalía el derecho global a copiar, usar, reproducir, modificar, adaptar, traducir, publicar, licenciar, distribuir, vender o asignar el Contenido de Usuario de cualquier forma que creamos conveniente, incluyendo pero no limitado a copiar en su totalidad o en parte, a la creación de trabajos derivados, distribuir y exhibir cualquier Contenido de Usuario en cualquier forma, medio, o tecnología, ya sea conocida o desarrollada en el futuro, sólo o como parte de otros trabajos, o utilizar el Contenido de Usuario en conexión con nuestros productos o servicios. Además, por la presente nos otorga el derechos a utilizar su nombre, imagen y semejanza para cualquier propósito de cualquier manera que lo creamos conveniente en su Contenido de Usuario.</p>
		<p>Todos los terceros, y no nosotros, son enteramente responsables por todo el Contenido de Usuario que se publique en la Aplicación. Usted se compromete a no participar o ayudar o animar a otros a participar en la transmisión , subir, publicar, enviar por correo electrónico o de otra manera el Contenido de Usuario que (a) sea dañino, ilegal, amenazador, abusivo, acosador, agraviante, difamatorio, vulgar, obsceno, pornográfico, invasivo de privacidad, odioso o racial, étnico o de cualquier otra forma; (b) usted no tiene el derecho de hacer disponible bajo ninguna ley o bajo relación contractual o fiduciaria; (c)<u>es conocido por usted que sea falso, inexacto o engañoso;</u> (d) <u>haya recibido una compensación o concedido cualquier consideración por parte de terceros;</u> o (e) infrinja cualquier patente, marca comercial, secreto comercial, derecho de autor u otros derechos de propiedad de cualquier parte. Además usted se compromete a no transmitir, cargar, publicar, enviar por correo, o poner a disposición cualquier tipo de virus de software, publicidad no solicitada o no autorizada, solicitud o material promocional, incluyendo cartas en cadena, correos masivos o cualquier forma de "spam". Asimismo, acepta no (I) hacerse pasar por otra persona o entidad, o declarar falsamente o desfigurar su afiliación con cualquier persona o entidad, (ii) "acechar" o acosar <u>incluyendo abogar acoso de otro, atrapar o dañar cualquier tercero,incluyendo dañar a menores de cualquier manera,</u> (iii) falsificar encabezados o manipular identificadores para disfrazar el origen de cualquier contenido de usuario, (iv) con o sin intención violar cualquier ley local, estatal, nacional o internacional, o (v) recoger o almacenar datos de identificación personal acerca de otros usuarios.</p>
		<p>Nosotros no evaluamos ni controlamos el Contenido de Usuario transmitido o publicado en la Aplicación y, por tanto no garantizamos la exactitud, integridad o calidad del Contenido de Usuario. Usted entiende que al usar la Aplicación, usted puede estar expuesto a Contenido de Usuario que es ofensivo, indecente u objetable para usted. En ningún caso seremos responsables de ninguna manera por cualquier Contenido de Usuario, incluyendo sin limitación, cualquier error y omisión en cualquier Contenido de Usuario, o por cualquier pérdida daño de cualquier tipo incurridos por usted como resultado del uso de cualquier Contenido del Usuario transmitido, cargado, publicado, enviado por correo electrónico o puesto a disposición a través de la aplicación.</p>
		<p>No somos de ninguna manera responsables de examinar o evaluar la acción en la que usted y su Círculo de Fortaleza ha accedido a participar, ni estamos obligados a respaldar su acción o Círculo de Fortaleza. No asumimos ninguna responsabilidad por la selección o finalización de la acción o de la falta de completar la acción de usted o de cualquiera en su Círculo de Fortaleza.<br/>
		Usted acepta que tenemos el derecho (pero no la obligación), a nuestra única discreción, de negarse  a publicar o eliminar cualquier Contenido de Usuario y nos reservamos el derecho de cambiar, condensar, o eliminar cualquier Contenido de Usuario. Sin limitar la generalidad de lo anterior o de cualquier otra disposición de estos Términos y Condiciones, nos reservamos el derecho de eliminar cualquier contenido de usuario que viole estos Términos y Condiciones o sea de dudosa reputación y nos reservamos el derecho de rechazar el servicio sin previo aviso y por cualquier usuario que viole estos Términos y Condiciones o infrinja los derechos de otros.
		</p>

		<h3>7. Reclamaciones por Derechos de Autor</h3>
		<p>Respetamos la propiedad intelectual de otros. Si usted cree que los materiales con derechos de autor se han copiado de una manera que constituye una infracción de copyright, por favor envíe un correo electrónico o una notificación por escrito a nuestro Agente designado para las notificaciones de infracción y proporcionar lo siguiente: (I) Identificación de la obra con derechos de autor(es) que usted afirma han sido violadas y la confirmación de que usted es el propietario del copyright o autorizado para actuar en nombre del dueño del copyright; (ii) una descripción material que considera que infringe y la ubicación de ese material en el Sitio, (iii) su dirección, número de teléfono y dirección de correo electrónico.</p>
		<p><strong>Nuestro agente designado para la notificación de reclamaciones de infracción de derechos de autor es Gregg Marrazzo, Senior Vice President and Deputy General Counsel, The Estée Lauder Companies Inc., 767 Fifth Avenue, New York, N.Y.  10153.  Teléfono: (212) 277-2320.  Email: gmarrazz@estee.com.</strong></p>
		<p>NOTA: La información de contacto anterior se proporciona exclusivamente para notificar a The Estée Lauder Companies que los derechos de autor pudiesen haber sido infringidos. Cualquier otra consulta no recibirá una respuesta a través de este proceso y deben ser dirigidas a nuestro grupo de servicio por e-mail a consumercare-us@gcc.elc.estee.com. [elcservicioaclientes@mx.estee.com]</p>

		<h3>8. Representaciones y garantías, limitación de responsabilidad</h3>
		<p>TLA APLICACIÓN SE PRESENTA "TAL CUAL". NO HACEMOS NINGUNA REPRESENTACIÓN O GARANTÍA DE NINGÚN TIPO, EXPRESA O ILÍCITA, EN RELACIÓN CON ESTOS TÉRMINOS Y CONDICIONES O DE LA APLICACIÓN, INCLUYENDO PERO NO LIMITANDO A LAS GARANTÍAS DE COMERCIALIZACIÓN, DE NO INFRACCION O IDONEIDAD PARA UN PROPÓSITO PARTICULAR, CON EXCEPCIÓN DE LO DECLARADO Y GARANTÍAS NO SON LEGALMENTE EXCLUIDAS.</p>
		<p>USTED ACEPTA QUE, EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY APLICABLE, NO SEREMOS RESPONSABLES (YA SEA EN CONTRATO, AGRAVIO (INCLUYENDO NEGLIGENCIA) O CUALQUIER OTRA FORMA), BAJO NINGUNA CIRCUNSTANCIA, POR DAÑOS (a) INTERRUPCIÓN DE NEGOCIO, (B) DEMORAS O INTERRUPCIONES EN EL ACCESO A LA APLICACIÓN, (C)FALTA DE ENTREGA, ENTREGA INCORRECTA, CORRUPCIÓN, DESTRUCCIÓN, U OTRA MODIFICACIÓN, (D) PÉRDIDA O DAÑO DE  CUALQUIER TIPO INCURRIDO A CONSECUIENCIA DEL TRATAMIENTO O PRESENCIA DE ENLACES OFF-WEBAPPLICATION SOBRE LA APLICACIÓN, (E) VIRUS INFORMÁTICOS, FALLOS DEL SISTEMA O MAL FUNCIONAMIENTO QUE PUEDA OCURRIR EN RELACIÓN CON EL USO DE LA APLICACIÓN, INCLUSO DURANTE UN HYPERLINK DESDE WEBAPPLICATIONS DE TERCEROS, (F) CUALQUIER INEXACTITUD U OMISIÓN EN EL CONTENIDO O (g) EVENTOS MÁS ALLÁ DE NUESTRO CONTROL RAZONABLE.</p>
		<p>ADEMÁS, EN LA MEDIDA EN QUE LO PERMITA LA LEY, NO NOS HACEMOS RESPONSABLES POR CUALQUIER DAÑO INDIRECTO, ESPECIAL, INCIDENTAL O CONSECUENTE DE NINGÚN TIPO (INCLUYENDO PERDIDA DE GANANCIAS) RELACIONADOS A LA APLICACIÓN O SU USO SIN IMPORTAR LA FORMA DE ACCIÓN YA SEA EN CONTRATO, AGRAVIO (INCLUYENDO NEGLIGENCIA) O DE CUALQUIER OTRA FORMA, AÚN CUANDO HEMOS SIDO ADVERTIDO DE LA POSIBILIDAD DE DICHOS DAÑOS Y EN NINGÚN CASO NUESTRA RESPONSABILIDAD TOTAL EXCEDERÁ CIEN DOLARES (100.00 USD.)</p>
		<p>USTED ACEPTA QUE NINGUNA RECLAMACIÓN O ACCIÓN QUE SURJA DE O EN RELACIÓN CON EL USO DE LA APLICACIÓN O DE ESTOS TÉRMINOS Y CONDICIONES PUEDEN SER LLEVADOS POR USTED POR MÁS DE (1) AÑO DESPUES DE LA CAUSA DE ACCIÓN RELACIONADA CON DICHA DEMANDA O ACCIÓN SURGIDA.</p>

		<h3>9. Indemnificación</h3>
		<p>Usted acepta defender, indemnizar y mantener en paz salvo de cualquier pérdida, daños o gastos, incluyendo los honorarios razonables de abogados, resultantes de cualquier reclamación de terceros, acción o demanda resultante del uso de la aplicación o incumplimiento de estos Términos y Condiciones. También acepta a indemnizarnos por cualquier pérdida, daños o gastos, incluyendo los honorarios razonables de abogados, que resulten de la utilización de robots informáticos, arañas, rastreadores, o similares de recopilación y herramientas de extracción, o cualquier otra acción que usted tome  que imponga una carga irrazonable en nuestra infraestructura.</p>

		<h3>10. Disputas</h3>
		<p>Con respecto a cualquier controversia relativa a la aplicación, todos los derechos y obligaciones y todas las acciones contempladas en estos Términos y Condiciones se regirán por las leyes de Nueva york, como si los términos y condiciones son un contrato totalmente suscrito y realizadas completamente en Nueva York. Cualquier disputa relacionada de cualquier manera con su visita a la Aplicación será sometida a arbitraje confidencial en Nueva York y someterse a la juridicción y los procedimientos de la misma, excepto a la medida que usted de cualquier forma haya violado o amenazado con violar la propiedad intelectual o los derechos de propiedad intelectual de nuestros afiliados, socios o lincenciantes, o de otra manera tienen una causa de acción en el patrimonio neto, podemos pedir medidas cautelares u otro desagravio apropiado en cualquier tribunal de juridicción competente y usted consiente a la juridicción y competencia de cualquier tribunal para tal propósitos. El arbitraje bajo este acuerdo será conducido por la Ley de Disputas Referentes al Consumidor de acuerdo a la Asociación Americana de Arbitraje. El laudo arbitral será vinculante y puede ser introducido como sentencia en cualquier tribunal de juridicción competente. en la máxima medida permitida por la ley aplicable, ningún arbitraje bajo estos Términos y Condiciones será unido a un arbitraje con cualquier otra parte sujeta a estos Términos y Condiciones, ya sea a través de procedimientos de arbitraje o de otra manera.</p>

		<h3>11. General</h3>
		<p>Usted reconoce y acepta que estos Términos y Condiciones constituyen el acuerdo completo y exclusivo entre nosotros con respecto a su uso de la Aplicación, y sustituyen y gobiernan todas las propuestas, acuerdos u otras comunicaciones.</p>
		<p>Nos reservamos el derecho, a nuestra única discreción, de cambiar estos Términos y Condiciones en cualquier momento mediante la publicación de los cambios sobre la Aplicación y dar aviso de dicho cambio. Los cambios entrarán en vigor inmediatamente después de su publicación a la aplicación y la liberación de la notificación de dicho cambio. El uso contínuo de la Aplicación constituye a partir de entonces su aceptación a todos sus términos y condiciones modificados. Es posible que, con o sin previo aviso, terminar cualquiera de los derechos otorgados por estos Términos y Condiciones. Usted deberá cumplir inmediatamente con cualquier terminación o cualquier otro aviso, incluyendo, en su caso, el cese del uso de la Aplicación.</p>
		<p>Nada de lo contenido en los presentes Términos y Condiciones se interpretará como la creación de una agencia, sociedad o cualquier otra forma de empresa conjunta entre nosotros. Nuestra incapacidad para exigir el cumplimiento de cualquier disposición de este documento no afectará nuestro pleno derecho a exigir tal cumplimiento en cualquier momento posterior, ni será tomada o considerada como una renuncia a la propia disposición nuestra renuncia a un incumplimiento de cualquier disposición del mismo. En el caso de que cualquier disposición de estos Términos y Condiciones será inaplicable o nula en virtud de cualquier ley aplicable o en posesión de cualquier laudo arbitral o por una resolución judicial, dicha inaplicabilidad o invalidez no hará que las presentes Condiciones inaplicables o inválidas en su totalidad pero los presentes Términos y Condiciones se modifican, en lo posible, por la entidad contratante para reflejar más plenamente la intención original de las partes tal como se refleja en la disposición original.</p>
		<p>Si tiene cualquier duda respecto a estos Términos y Condiciones por favor contáctenos al: consumercare-us@gcc.elc.estee.com. elcservicioaclientes@mx.estee.com</p>

	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>