<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>2013 CAMPAÑA CONTRA EL CÁNCER DE MAMA: TÉRMINOS Y CONDICIONES DE USO INTERNACIONALESS</h2>
		<h3>Fecha de entrada en vigor: 1 de Agosto de 2013</h3>

		<p><strong>Bienvenido a la Campaña de Estée Lauder Companies Contra el Cáncer de Mama en Facebook de Welcome (en lo sucesivo <i>“La Aplicación"</i>).</strong></p>
		<p>Estée Lauder Companies Inc. pone a su disposición el contenido y los servicios que se encuentran en la Aplicación con sujeción a los siguientes Términos y Condiciones, a la Política de Privacidad y a otros terminus y condiciones y políticas que podrá encontrar en otras partes de la Aplicación en relación con determinadas características, funcionalidades o promociones y el servicio de atención al cliente, todos los cuales se consideran integrantes e incluidos en los presentes términos y condiciones (conjuntamente, <i><strong>“Términos y Condiciones”</strong></i>). Al utilizar o acceder a la Aplicación, reconoce que ha leído y entendido los presentes Términos y Condiciones y que ha aceptado quedar obligado por ellos sin ninguna limitación ni reserva.</p>

		<h3>1. Privacidad</h3>
		<p>Rogamos lea nuestra <i><strong>Política de Privacidad</strong></i> para conocer nuestras prácticas a este respecto.</p>

		<h3>2. Propiedad Intelectual</h3>
		<p>Excepto cualquier información o contenido propiedad de Facebook, Inc. al respecto del uso de esta plataforma, toda la información y los contenidos disponibles en la Aplicación y su “look and feel”, incluso, a título meramente enunciativo y no limitativo, marcas, logotipos, marcas de servicio, textos, gráficos, logos, iconos de botones, imágenes, clips de audio, recopilaciones de datos y software y su recopilación y organización (conjuntamente, los “Contenidos”) son propiedad de Estée Lauder Companies Inc., de nuestras entidades asociadas, socios comerciales o licenciantes y están protegidos por leyes estadounidenses e internacionales, incluidas aquellas que regulan los derechos de autor y las marcas.</p>
		<p>Con las excepciones contempladas en las licencias limitadas que se otorgan en el siguiente Apartado 3 o salvo en la medida en que lo requiera la legislación aplicable, ni los Contenidos ni ninguna de las partes del Sitio podrán usarse, reproducirse, duplicarse, copiarse, venderse, revenderse, accederse, modificarse o explotarse en otra forma, ni en todo ni en parte y para ningún fin, sin nuestro previo y expreso consentimiento por escrito.</p>

		<h3>3. Licencias Limitadas</h3>
		<p>Le concedemos una licencia limitada, revocable y no exclusiva para acceder a la Alicación y hacer un uso particular de la misma. Esta licencia limitada no incluye el derecho a: (a) enmarcar o usar técnicas de “framing” para encuadrar el Sitio o cualquier parte del mismo; (b) volver a publicar o distribuir, transmitir, vender, licenciar o descargar el Sitio o la totalidad o parte de los Contenidos (salvo caching o cuando sea necesario para visionar el Sitio); (c) hacer un uso del Sitio o de la totalidad o parte de los Contenidos que no sea personal; (d) modificar, someter a técnicas de ingeniería inversa o crear trabajos derivados del Sitio o de la totalidad o parte de los Contenidos; (e) recabar información de cuentas en su propio beneficio o en el de un tercero; (f) usar metatags o cualquier otro “texto oculto” mediante utilización de la totalidad o parte de los Contenidos; ni (g) a usar robots de software, spiders, arañas web o similares herramientas de recogida y extracción de datos, ni a realizar ninguna otra actuación que pueda hacer que nuestra estructura tenga que soportar una carga irrazonable. No podrá suprimir ni modificar ninguno de los avisos de propiedad que están incluidos o contenidos en la Aplicación.</p>
		<p>Todo uso no autorizado del Sitio y la Aplicación y de la totalidad o parte de nuestros Contenidos conllevará la extinción automática de las licencias limitadas establecidas en este <i><strong>Apartado 3</strong></i>, sin perjuicio de cualquier otra acción que nos corresponda en virtud de la legislación aplicable o de los presentes Términos y Condiciones.</p>

		<h3>4. Sus Obligaciones y Responsabilidades</h4>
		<p>Al acceder o usar la Aplicación deberá dar cumplimiento a los presentes Términos y Condiciones y a las advertencias o instrucciones especiales de acceso o uso incluidas en la misma. Deberá actuar en todo momento con arreglo a la ley, la costumbre y la buena fe. No podrá introducir ningún cambio o modificación en la Aplicación ni en los Contenidos o servicios incluidos en el mismo ni podrá afectar en forma alguna su integridad o funcionamiento. Sin limitar el carácter general de cualquier otra disposición de los presentes Términos y Condiciones y en los más amplios términos permitidos por la legislación aplicable, si incurriera en incumplimiento culpable o doloso de cualquiera de las obligaciones establecidas en los presentes Términos y Condiciones, responderá de todos los daños y perjuicios que Estée Lauder Companies o nuestras entidades asociadas, socios comerciales o licenciantes puedan sufrir por tal causa.</p>

		<h3>5. Enlaces de Tercero</h3>
		<p>No respondemos de los contenidos de páginas externas o de otros sitios que estén enlazados a o desde nuestra Aplicación. Los enlaces que aparecen en la Aplicación se incluyen con el único fin de facilitar la navegación, sin que constituyan recomendación por nuestra parte o por parte de nuestras entidades asociadas o socios comerciales de sus contenidos, productos, servicios o proveedores. Si utiliza enlaces a o desde páginas externas u otros sitios web, lo hará a su propio riesgo. No nos responsabilizamos de examinar o evaluar, ni garantizamos, los productos o servicios ofrecidos en páginas externas ni en otros sitios web enlazados a o desde el Sitio ni asumimos responsabilidad alguna por las acciones, contenidos, productos o servicios de tales páginas y sitios web, incluso, a título meramente enunciativo y no limitativo, los términos y condiciones y las políticas de privacidad. Debe examinar detenidamente los términos y condiciones y las políticas de privacidad de todas las páginas externas y otros sitios web que visite. Sin perjuicio de lo anterior, nos reservamos el derecho a suprimir enlaces a cualquier sitio si tenemos motivos para creer que las actividades que llevan a cabo o su contenido son ilegítimas o vulneran en otra forma derechos de tercero o cuando vengamos requeridos a hacerlo en virtud de resolución judicial o administrativa.</p>

		<h3>6. Contenidos de Usuario</h3>
		<p>En el caso de que transmita, suba, cuelgue, envíe por correo electrónico o facilite en otra forma datos, textos, software, música, sonido, fotografías, gráficos, imágenes, vídeos, mensajes u otros materiales (<i><strong>“Contenidos de Usuario”</strong></i>) en la Aplicación, será usted el único responsable de tales Contenidos de Usuario. Se obliga usted a abstenerse, y a hacer que cualquier tercero se abstenga, de transmitir, subir, colgar, enviar por correo electrónico o en otra forma facilitar en la Aplicación Contenidos de Usuario que, entre otras cosas, (a) sean ilegales, perniciosos, amenazantes, abusivos, acosadores, torticeros, difamatorios, vulgares, obscenos, pornográficos, injuriosos, invasores de la privacidad, execrables o censurables desde un punto de vista racial, étnico o cualquier otro; (b) no esté legitimado para facilitar en virtud de ley, contrato o relación fiduciaria; (c) le conste que son falsos, inexactos o engañosos; (d) en relación con los cuales haya percibido contraprestación de un tercero; o (e) que vulneren patentes, marcas, secretos comerciales, derechos de autor u otros derechos de propiedad de un tercero. Se obliga, asimismo, a no transmitir, subir, colgar enviar por correo electrónico o en otra forma facilitar virus de software, anuncios no solicitados o no autorizados, ofertas o materiales promocionales, incluidos mensajes en cadena, correos masivos o cualquier otra forma de “spam”. Se obliga además a no (i) hacerse pasar por otra persona física o jurídica o falsear su relación con cualquier persona física o jurídica; (ii) acosar, incluso propugnar el acoso, de un tercero, engañar o perjudicar a un tercero, incluidos daños a menores en cualquier forma; (iii) falsificar cabeceras o en otra forma manipular identificadores con el fin de ocultar el origen de Contenidos de Usuario; (iv) incumplir, voluntaria o involuntariamente, leyes locales, nacionales o internacionales o (v) recabar o almacenar datos que permitan la identificación personal de otros usuarios.</p>
		<p>No refrendamos ni controlamos los Contenidos de Usuario que se transmiten o cuelgan en la Aplicación y, por lo tanto, no garantizamos su exactitud, integridad o calidad. Entiende usted que al usar la Aplicación puede quedar expuesto a Contenidos de Usuario que sean ofensivos, indecentes o inaceptables para usted. No responderemos en ningún caso de Contenidos de Usuario, incluso, a título enunciativo y no limitativo, de errores u omisiones en Contenidos de Usuario ni de daños y perjuicios de cualquier tipo en que incurra como resultado del uso de Contenidos de Usuario transmitidos, subidos, colgados, enviados por correo electrónico o facilitados en otra forma a través de la Aplicación.</p>
		<p>Reconoce que tenemos el derecho (pero no la obligación), a nuestra exclusiva discreción, a negarnos a colgar o suprimir Contenidos de Usuario que, de buena fe, consideremos que vulneran las disposiciones precedentes y nos reservamos el derecho a cambiar, compendiar o suprimir cualesquiera Contenidos de Usuario. Sin limitar el carácter general de lo anterior o cualesquiera otras disposiciones de los presentes Términos y Condiciones, estamos legitimados para suprimir Contenidos de Usuario que vulneren los presentes Términos y Condiciones o que sean inaceptables por cualquier otro motivo y nos reservamos el derecho a negar servicios o cancelar cuentas sin previo aviso a usuarios que incumplan estos Términos y Condiciones o que infrinjan derechos de tercero.</p>
		<p>Sujeto a los términos de nuestra Política de Privacidad, mediante la transmisión o post de Contenidos de Usuario, está de acuerdo en garantizar Contenido de Usuario no exclusivo, transferible, bajo licencia, sin patentes, con licencia mundial para copiar, utilizar, reproducir, modificar, adaptar, traducir, publicar, hacerle licencia, distribuir, vender o asignar de cualquiera manera que nosotros consideremos oportuna, incluyendo el poder copiar este contenido en su totalidad o en parte, creando trabajos derivados de ello, distribuyendo y publicitando este Contenido en cualquier forma, en cualquier medio o cualquier tecnología ahora conocida o todavía por desarrollar, solo o como parte de otros trabajos, o utilizar este Contenido de Usuario dentro de una conexión con nuestros productos o servicios. Además, garantiza el derecho a que utilicemos su nombre, imagen y parecido para cualquier fin que consideremos oportuno en relación con su Contenido de Usuario.</p>

		<h3>7. Quejas relativas a Derechos de Autor</h3>
		<p>Respetamos la propiedad intelectual de terceros. Si considera que se ha copiado una obra en el Sitio o en la Aplicación y que como resultado se han vulnerando derechos de autor, continúe leyendo para saber cómo nos tiene que notificar cualquier reclamación de infracción, incluyendo la siguiente información: (i) identificación de lo(s) trabajo(s) con copyright que cree que se han infringido y confirmación de que usted es el poseedor de los derechos de copyright de los mismos o que actúa en nombre del poseedor de tales derechos; (ii) descripción del material que cree que se ha infringido y la localización de ese material en el Sitio o Aplicación; (iii) su dirección, teléfono y dirección de correo electrónico.</p>
		<p><strong>Contace con nuestro servicio de Atención al Cliente para notificarlo y seguir sus instrucciones para la resolución de dicha queja. consumercare-es@gcc.esteelauder.com</strong></p>

		<h3>8. Declaraciones y Garantías; Limitación de Responsabilidad</h3>
		<p>EL SITIO SE PRESENTA “AS IS”. NO OTORGAMOS NINGUNA DECLARACIÓN NI GARANTÍA, SEA TÁCITA O EXPRESA, EN RELACIÓN CON LOS PRESENTES TÉRMINOS Y CONDICIONES O EL SITIO, INCLUIDAS, ENTRE OTRAS, GARANTIAS DE COMERCIABILIDAD, AUSENCIA DE INFRACCIÓN O IDONEIDAD PARA UN DETERMINADO FIN, SALVO EN LA MEDIDA EN QUE LA LEY NO PERMITA EXCLUIR TALES DECLARACIONES Y GARANTÍAS.</p>
		<p>CONVIENE USTED QUE, EN LA MÁXIMA MEDIDA EN QUE LO PERMITA LA LEGISLACIÓN APLICABLE, EN NINGÚN CASO INCURRIREMOS EN RESPONSABILIDAD (YA SEA CONTRACTUAL, EXTRACONTRACTUAL (INCLUIDA NEGLIGENCIA) O DE OTRA NATURALEZA) COMO CONSECUENCIA DE (a) INTERRUPCIÓN DE ACTIVIDAD COMERCIAL; (b) RETRASO O INTERRUPCIÓN EN EL ACCESO AL SITIO; (c) FALTA DE ENTREGA, ENTREGA ERRÓNEA, CORRUPCIÓN, DESTRUCCIÓN U OTRA MODIFICACIÓN DE DATOS; (d) PÉRDIDAS O DAÑOS DE CUALQUIER TIPO DERIVADOS DEL USO O DE LA PRESENCIA DE ENLACES EXTERNOS EN EL SITIO; (e) VIRUS, FALLOS O MAL FUNCIONAMIENTO DEL SISTEMA EN RELACIÓN CON EL USO DEL SITIO POR SU PARTE, INCLUIDO EL USO DE HIPERENLACES A O DESDE SITIOS WEB DE TERCERO (f) CONTENIDO INEXACTO U OMITIDO O (g) ACONTECIMIENTOS QUE ESTÉN FUERA DE NUESTRO CONTROL RAZONABLE.</p>
		<p>EN LA MÁS AMPLIA MEDIDA EN QUE LO PERMITA LA LEY, NO ASUMIREMOS RESPONSABILIDAD, YA SEA CONTRACTUAL, EXTRACONTRACTUAL (INCUIDA NEGLIGENCIA) O DE OTRA NATURALEZA, POR DAÑOS INDIRECTOS, CUANTIFICABLES, PUNITIVOS, INCIDENTALES O CONSECUENTES (INCLUIDO LUCRO CESANTE) QUE ESTÉN RELACIONADOS CON EL SITIO O CON EL USO DEL MISMO POR SU PARTE, AÚN CUANDO HAYAMOS SIDO ADVERTIDOS DE LA POSIBILIDAD DE QUE SE PRODUZCAN, SIN QUE NUESTRA RESPONSABILIDAD GLOBAL MÁXIMA EXCEDA LA CANTIDAD DE CIEN EUROS (€100).</p>
		<p>CONVIENE USTED QUE NO PODRÁ INTERPONER ACCIONES LEGALES O DEMANDAS EN RELACIÓN CON EL USO DEL SITIO O CON LOS PRESENTES TÉRMINOS Y CONDICIONES UNA VEZ TRANSCURRIDO UN (1) AÑO DESDE QUE SE HAYA ORIGINADO LA CAUSA DE LA DEMANDA.</p>
		<p>SIN PERJUICIO DE LO ANTERIOR, ASUMIREMOS RESPONSABILIDAD EN CASO DE DAÑOS QUE TRAIGAN CAUSA DE DOLO O CULPA GRAVE, RESPONSABILIDAD CIVIL POR PRODUCTOS DEFECTUOSOS Y, EN GENERAL, CUALQUIER TIPO DE RESPONSABILIDAD QUE LA LEGISLACIÓN APLICABLE NO PERMITA EXCLUIR.</p>
		<p>POR OTRA PARTE, PUEDE QUE ALGUNAS DE LAS LIMITACIONES ESTABLECIDAS EN ESTA CLÁUSULA NO LE SEAN DE APLICACIÓN, EN AQUELLOS CASOS EN QUE TENGA CONSIDERACIÓN DE CONSUMIDOR A TENOR DE LA LEGISLACIÓN APLICABLE.</p>

		<h3>9. Indemnización</h3>
		<p>Se le obliga usted a defendernos, indemnizarnos y mantenernos indemnes frente a cualesquiera pérdidas, daños o costes, incluidos honorarios razonables de abogados, que traigan causa de reclamación, acción o demanda de tercero interpuesta como consecuencia del uso del Sitio o del incumplimiento de los presentes Términos y Condiciones por su parte. Se obliga asimismo a indemnizarnos por las pérdidas, daños o costes, incluidos honorarios razonables de abogados, que resulten del uso por su parte de robots de software, spiders, arañas web o herramientas similares de recogida y extracción de datos o cualquier otra actuación que haga que nuestra infraestructura deba soportar una carga irrazonable.</p>

		<h3>10. Conflictos</h3>
		<p>Los derechos y obligaciones que le corresponden en relación con este Sitio estarán regulados por la legislación española. Cualquier conflicto relacionado con el Sitio se someterá a Arbitraje de Consumo en España. El arbitraje será de derecho. En la máxima medida permitida por la legislación española, ningún procedimiento arbitral iniciado a tenor de los presentes Términos y Condiciones podrá acumularse a otro procedimiento arbitral que afecte a otra parte sujeta a los mismos, ya sea mediante procedimientos arbitrales colectivos o en otra forma. Sin perjuicio de lo anterior, en tanto en cuanto haya vulnerado o amenazado con vulnerar nuestros derechos de propiedad intelectual o aquellos de nuestras entidades asociadas, socios comerciales o licenciantes o si por cualquier otra causa nos corresponden acciones en equidad, podremos solicitar medidas cautelares u otras medidas oportunas ante cualquier tribunal competente, cuya jurisdicción y competencia acepta usted a tales efectos. La aceptación de las referidas medidas no se entenderá en ningún caso como la renuncia a nuestro derecho a someter un conflicto a arbitraje. En tanto en cuanto la legislación aplicable no permita el arbitraje, cualquier conflicto relativo a este Sitio se someterá a los juzgados y tribunales competentes en España.</p>

		<h3>11. General</h3>
		<p>Reconoce y conviene que los presentes Términos y Condiciones constituyen la totalidad de lo acordado entre nosotros en relación con el uso del Sitio por su parte y sustituyen y anulan todas las anteriores propuestas, contratos u otras comunicaciones.</p>
		<p>Nos reservamos el derecho, a nuestra exclusiva discreción, a modificar en cualquier momento los presentes Términos y Condiciones mediante la inclusión de los correspondientes cambios en el Sitio y mediante la notificación de tales cambios. Los cambios surtirán efectos inmediatos al incluirse en el Sitio y al enviarse la correspondiente notificación. El uso del Sitio después del cambio constituirá la aceptación de los Términos y Condiciones modificados. Podremos proceder, con aviso o sin él, a la cancelación de cualquiera de los derechos que se conceden en estos Términos y Condiciones. Deberá dar cumplimiento inmediato a cualquier notificación de cancelación o de otro tipo, incluso, en su caso, dejando de usar el Sitio.</p>
		<p>Nada de lo establecido en los presentes Términos y Condiciones deberá interpretarse en el sentido de crear una agencia, “partnership” u otra forma de negocio conjunto entre nosotros. El hecho de que no exijamos el cumplimiento de cualquiera de los presentes términos no afectará a nuestro derecho a exigirlo en un momento posterior y la renuncia a reclamar por el incumplimiento de cualquiera de los presentes términos no deberá entenderse como renuncia al término en cuestión. En el supuesto de que cualquiera de las disposiciones de los presentes Términos y Condiciones fuera inexigible o nula en virtud de la legislación aplicable o de laudo arbitral o resolución judicial, ello no afectará al conjunto de los Términos y Condiciones, que se modificarán, en la medida posible, en la forma que más se aproxime a la intención original de las partes reflejada en la disposición original.</p>
		<p>En caso de duda con respecto a los presentes Términos y Condiciones, rogamos envíe un correo electrónico a NOTIFICACIÓN DE LA POLÍTICA SOBRE INFRACCIÓN DE DERECHOS DE AUTOR</p>
		<p>Si considera que se han copiado materiales sujetos a derechos de autor y como resultado se infringen derechos de autor, rogamos envíe un correo electrónico o notificación por escrito a nuestro Agente Designado para notificaciones de infracción, con inclusión de lo siguiente:<br/>Firma física o electrónica de una persona autorizada a actuar en nombre del titular de los derechos de autor objeto de la supuesta infracción;<br/>Identificación de la obra u obras sujetas a derechos de autor supuestamente infringidos;<br/>Descripción del material supuestamente infractor y el lugar del Sitio en que se encuentra;<br/>Su dirección, número de teléfono y dirección de correo electrónico;<br/>Declaración en el sentido de que considera de buena fe que el uso del material en la forma objeto de queja no está autorizado por el titular de los derechos de autor, su agente o la ley; y<br/>Declaración, con sujeción a la pena que corresponda en caso de perjurio, en el sentido de que la información contenida en su notificación es exacta y que es usted el titular de los derechos de autor o la persona autorizada a actuar en nombre de dicho titular.</p>
		<p>NOTA: LA ANTERIOR INFORMACIÓN DE CONTACTO SE FACILITA CON EL ÚNICO FIN DE NOTIFICAR A M∙A∙C COSMETICS SPAIN ONLINE LA POSIBLE INFRACCIÓN DE MATERIAL SUJETO A DERECHOS DE AUTOR. NINGUNA OTRA CONSULTA ENVIADA POR ESTA VÍA RECIBIRÁ RESPUESTA, DEBIENDO DIRIGIRSE A NUESTRO GRUPO DE ATENCIÓN AL CLIENTE POR CORREO ELECTRÓNICO A: consumercare-es@gcc.esteelauder.com</p>

	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>