<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>CAMPANHA SCM 2013: TERMOS E CONDIÇÕES INTERNACIONAIS</h2>
		<h3>Data de entrada em vigor: 1 de Agosto de 2013</h3>

		<p><strong>Bem-vindo à aplicação de Facebook da Campanha de Sensibilização para o Cancro da Mama da The Estée Lauder Companies (a <i>"aplicação"</i>).</strong></p>
		<p>Nós, Estée Lauder Companies Inc., fornecemos os conteúdos e serviços disponíveis na aplicação ao participante de acordo com os termos e as condições abaixo, a nossa política de privacidade e outros termos, bem como outras condições e políticas que o participante poderá encontrar na Aplicação no âmbito de determinada funcionalidade, atributo ou promoção, bem como do serviço ao cliente, sendo tudo o que atrás se descreve considerado uma parte integrante dos presentes termos e condições (na totalidade, <i><strong>“termos e condições”</strong></i>). Ao aceder ou dar uso à aplicação, o participante confirma que leu e compreende os termos e as condições, e que acorda respeitá-los sem limitações, nem reservas.</p>

		<h3>1. Privacidade</h3>
		<p>Por favor, leia a nossa <strong>política de privacidade</strong> para que possa compreender as nossas práticas de privacidade.</p>

		<h3>2. Propriedade intelectual</h3>
		<p>Salvo qualquer informação e / ou conteúdo fornecido pelo Facebook, Inc. relativamente à utilização da respectiva plataforma, toda a informação e todo o conteúdo restante disponível na aplicação e a “aparência e impressão geral” da aplicação, incluindo, entre outros, as marcas registadas, os logos, as marcas de serviço, o texto, o grafismo, os ícones, as imagens, os clipes de áudio, as compilações de dados e o software, bem como a compilação e organização dos elementos referidos (na totalidade, o <i><strong>“conteúdo”</strong></i>), é propriedade da The Estée Lauder Companies Inc., ou filiais, parceiros ou entidades licenciadoras, sendo protegido pela legislação dos Estados Unidos e internacional, incluindo a legislação que rege os direitos de autor e as marcas registadas.</p>

		<h3>3. Licenças limitadas</h3>
		<p>Concedemos ao participante uma licença limitada, revogável e não exclusiva para aceder à aplicação e fazer uso pessoal da mesma. A referida licença limitada não inclui o direito a: (a) enquadrar ou utilizar técnicas de enquadramento para envolver a aplicação ou qualquer parte da mesma; (b) republicar, redistribuir, transmitir, vender, licenciar ou descarregar a aplicação ou uma parte e / ou a totalidade do conteúdo (com excepção do procedimento de caching ou de outro procedimento necessário para ver a aplicação); (c) utilizar a aplicação ou uma parte e / ou a totalidade do conteúdo para qualquer uso que não seja o uso pessoal; (d) modificar, usar engenharia inversa ou criar quaisquer obras derivadas com base na aplicação ou em parte ou / e na totalidade do conteúdo; (e) recolher informação da conta para benefício próprio ou de terceiros; (f) usar quaisquer metadados ou qualquer outro “texto escondido” utilizando uma parte e / ou a totalidade do conteúdo; ou (g) utilizar robots de software, spiders, rastreadores ou ferramentas de recolha e extracção de dados afins, ou agir de qualquer outro modo que possa significar um peso excessivo ou uma sobrecarga da nossa infra-estrutura. O participante terá de manter, sem alteração, todas as indicações de direitos de autor da aplicação, ou anexadas à aplicação ou contidas na aplicação</p>
		<p>Qualquer uso não autorizado da aplicação ou de parte e / ou da totalidade do conteúdo põe automaticamente termos às licenças limitadas apresentadas na presente Artigo 3, sem prejuízo de qualquer outro remédio nos termos da legislação aplicável ou dos presentes termos e condições.</p>

		<h3>4. As obrigações e responsabilidades do participante</h4>
		<p>Ao aceder ou utilizar a aplicação, o participante terá de cumprir os presentes termos e condições e os avisos ou as instruções especiais para acesso ou uso publicados na aplicação. O participante deverá agir sempre em conformidade com a lei e os costumes, e em boa fé. O participante não poderá fazer qualquer mudança ou alteração à Aplicação nem a qualquer Conteúdo ou a quaisquer serviços que poderão aparecer na Aplicação e não poderá danificar de forma nenhuma a integridade ou o funcionamento da Aplicação. Sem limitar a generalidade de qualquer outra disposição dos presentes Termos e Condições, se o participante incumprir por negligência ou voluntariamente alguma das obrigações estabelecidas nos presentes Termos e Condições, será responsabilizado por todas as perdas e todos os danos que o incumprimento causar à The Estée Lauder Companies ou filiais, parceiros ou entidades licenciadoras.</p>

		<h3>5. Ligações de terceiros</h3>
		<p>Nós não somos responsáveis pelo conteúdo de qualquer página de um sítio web externo ou de quaisquer outros sítios web com ligação para a aplicação ou para os quais a aplicação disponibilize ligação. As ligações constantes na aplicação servem apenas para maior conveniência, e não significam que nós, as nossas filiais ou os nossos parceiros damos apoio ao conteúdo, produto, serviço ou fornecedor referenciado. É da exclusiva responsabilidade do participante clicar em qualquer ligação para qualquer sítio web externo ou a partir de qualquer sítio web externo. Não somos, de forma nenhuma, responsáveis pela análise ou avaliação das ofertas de páginas de sítios web externos ou de quaisquer outros sítios web com ligação para a aplicação ou para os quais a aplicação disponibilize ligação, nem garantimos as referidas ofertas, nem assumimos nenhuma responsabilidade ou obrigação relativamente às acções, ao conteúdo, aos produtos ou aos serviços das referidas páginas ou sítios web, incluindo, entre outros, as políticas de privacidade e os termos e as condições dos referidos sítios web. O participante deverá ler cuidadosamente os termos e as condições e as políticas de privacidade de todas as páginas de sítios web externos e de outros sítios web que visite.</p>

		<h3>6. Conteúdo do utilizador</h3>
		<p>Quando transmite, carrega, publica, envia por correio electrónico ou disponibiliza de outro modo dados, texto, software, música, som, fotografias, grafismos, imagens, vídeos, mensagens ou outros materiais (<i><strong>“conteúdo do utilizador”</strong></i>) na aplicação, o participante é inteiramente responsável pelo referido conteúdo do utilizador. Temos como política recusar sugestões e ideias não solicitadas. Não obstante a nossa política relativamente a sugestões e ideias não solicitadas, quaisquer questões, reacções, sugestões, ideias ou outras informações que o participante nos fornecer (na totalidade, “contribuições”) serão consideradas livres de direitos de autor e não confidenciais. Informamos também que as contribuições dos participantes não serão alvo de resposta e que poderemos utilizar as contribuições, e quaisquer ideias, conceitos ou competências incluídas nas mesmas, sem pagamento de dinheiro ou de qualquer outra forma de remuneração, para nenhum fim, incluindo, entre outros, o desenvolvimento, o fabrico, a distribuição e a comercialização de produtos. As contribuições serão tratadas como conteúdo do utilizador. </p>
		<p>Nos termos da nossa <strong>política de privacidade</strong>, ao transmitir ou publicar qualquer conteúdo do utilizador, o participante concede-nos, pelo presente, uma licença não exclusiva, transferível, sub-licenciável e livre de direitos de autor para copiar, usar, reproduzir, modificar, adaptar, traduzir, publicar, licenciar, distribuir, vender ou consignar o conteúdo do utilizador da forma que considerarmos adequada, incluindo, entre outros, a cópia da totalidade ou de parte, a criação de obras derivadas, a distribuição e a exibição de qualquer conteúdo do utilizador por qualquer forma, meio ou tecnologia, actualmente conhecida ou desenvolvida no futuro, individualmente ou como parte de outras obras; ou para utilizar o conteúdo do utilizador nos nossos produtos ou serviços ou em conjunto com os nossos produtos ou serviços. Além disso, pelo presente, o participante concede-nos o direito de utilizar o nome, a imagem e o retrato para qualquer fim, da forma que considerarmos adequada juntamente com o conteúdo do utilizador</p>
		<p>Todos os terceiros, e não nós, são inteiramente responsáveis por todo o conteúdo do utilizador que publiquem na aplicação. O participante acorda não envolver-se nem ajudar ou incentivar outros a envolver-se na transmissão, no carregamento, na publicação, no envio por correio electrónico ou na disponibilização por outro meio na aplicação de conteúdo do utilizador (a) que seja ilegal, danoso, ameaçador, abusivo, perturbador, lesivo, difamatório, vulgar, obsceno, pornográfico, calunioso, invasivo da privacidade de terceiros, odioso, ou objectável do ponto de vista racial, étnico ou outro; (b) que o participante não tenha o direito de disponibilizar nos termos de qualquer legislação ou nos termos de contratos ou relações fiduciais; (c) <u>que o participante saiba ser falso, impreciso, ou enganador;</u> (d) <u>pelo qual o participante seja compensado ou receba qualquer contribuição de qualquer terceiro;</u> ou (e) que viole qualquer patente, marca registada, segredo comercial ou outros direitos de propriedade de um terceiro. Além disto, acorda não transmitir, carregar, publicar, enviar por correio electrónico ou disponibilizar de outro modo quaisquer vírus de software, publicidade não solicitada nem autorizada, solicitação ou material promocional, incluindo cartas em cadeia, correspondência em massa ou qualquer forma de spam. Acorda ainda não (i) se fazer passar por nenhuma pessoa ou entidade, ou declarar erroneamente ou deturpar a sua filiação com qualquer pessoa ou entidade; (ii) “perseguir” ou assediar de outro modo, <u>incluindo invocando a assédio por parte de terceiros,</u> ludibriar ou lesar qualquer terceiro incluindo <u>lesar menores de alguma maneira</u>; (iii) falsificar cabeçalhos ou manipular de outro modo elementos identificadores de forma a disfarçar a origem de qualquer conteúdo do utilizador; (iv) violar qualquer lei local, estadual, nacional ou internacional aplicável intencional ou não intencionalmente, ou (v) recolher ou guardar dados pessoais identificáveis sobre outros utilizadores.</p>
		<p>Nós não patrocinamos nem controlamos o conteúdo de utilizador transmitido ou publicado na aplicação e, por conseguinte, não asseguramos a precisão, a integridade ou a qualidade do conteúdo de utilizador. Reconhecemos que, ao utilizar a aplicação, o participante pode ser exposto a conteúdo de utilizador que seja ofensivo, indecente ou objectável para o participante. Não seremos responsáveis em nenhuma circunstância e de nenhum modo por qualquer tipo de conteúdo do utilizador, incluindo, entre outros, quaisquer erros ou omissões em qualquer conteúdo de utilizador, nem por nenhuma perda ou dano de qualquer tipo em que o participante incorra como consequência do uso de qualquer conteúdo do utilizador transmitido, carregado, publicado, enviado por correio electrónico ou disponibilizado de outro modo na aplicação.</p>
		<p>Não temos qualquer responsabilidade na análise nem na avaliação da acção que o participante e o respectivo círculo de resistência concordaram encetar, nem estamos obrigados a patrocinar a acção ou o círculo de resistência do participante. Não assumimos qualquer responsabilidade ou obrigação relativamente à selecção ou à finalização da acção do participante ou relativamente à não finalização da acção por parte do participante ou do respectivo círculo de resistência.<br/>
		Confirmamos que temos o direito (mas não a obrigação) de, segundo o nosso critério exclusivo, recusar a publicação ou a remoção de qualquer conteúdo do utilizador, e reservamo-nos o direito de alterar, condensar ou apagar qualquer conteúdo do utilizador. Sem limitar o carácter geral das disposições acima ou de quaisquer outras disposições dos presentes termos e condições, temos o direito de remover qualquer conteúdo do utilizador que viole os presentes termos e condições ou que seja objectável de qualquer outra forma, e reservamo-nos o direito de recusar o serviço sem aviso prévio a quaisquer participantes que violem os presentes termos e condições ou que infrinjam os direitos de terceiros.</p>

		<h3>7. Reivindicações de direitos de autor</h3>
		<p>Respeitamos a propriedade intelectual de terceiros. Se considera que foram copiados materiais sujeitos a direitos de autor de uma forma que constitua violação dos direitos de autor, envie-nos, por favor, uma mensagem de correio electrónico para o nosso agente designado para avisos de infracção, indicando o seguinte: (i) identificação da(s) obra(s) cujos direitos de autor considera que foram violados e confirmação de que é o titular dos direitos de autor ou de que tem autorização para agir em representação do titular dos direitos de autor; (ii) uma descrição do material que considera estar a violar os direitos de autor e a localização do material no sítio web; (iii) a sua morada, o número de telefone e o endereço de correio electrónico.</p>
		<p><strong>O nosso agente designado para avisos de reivindicações de violação dos direitos de autor é Gregg Marrazzo, vice-presidente principal e consultor geral adjunto, The Estée Lauder Companies Inc., 767 Fifth Avenue, New York, N.Y. 10153. Telefone: (212) 277-2320. Endereço de correio electrónico: gmarrazz@estee.com.</strong></p>
		<p>NOTA: A INFORMAÇÃO DE CONTACTO ACIMA É FORNECIDA EXCLUSIVAMENTE PARA NOTIFICAR A AVEDA DE QUE PODEM TER SIDO VIOLADOS DIREITOS DE AUTOR. TODAS AS OUTRAS QUESTÕES NÃO TERÃO RESPOSTA ATRAVÉS DO PRESENTE PROCESSO E DEVEM SER DIRIGIDAS AO NOSSO GRUPO DE SERVIÇO DE APOIO AO CLIENTE POR MENSAGEM DE CORREIO ELECTRÓNICO PARA consumercare-us@gcc.elc.estee.com. [INSERIR A MORADA DO MERCADO LOCAL].</p>

		<h3>8. Declarações e garantias; limitação de responsabilidade</h3>
		<p>A APLICAÇÃO É APRESENTADA “TAL COMO ESTÁ”. NÃO FAZEMOS DECLARAÇÕES NEM DAMOS GARANTIAS DE NENHUM TIPO, EXPRESSAS OU IMPLÍCITAS, NO ÂMBITO DOS PRESENTES TERMOS E CONDIÇÕES OU DA APLICAÇÃO, INCLUINDO, ENTRE OUTRAS, GARANTIAS DE COMERCIABILIDADE, NÃO CONTRAFACÇÃO OU ADEQUAÇÃO PARA UM FIM PARTICULAR, EXCEPTO NA MEDIDA EM QUE NÃO SEJA POSSÍVEL EXCLUIR LEGALMENTE AS REFERIDAS DECLARAÇÕES E GARANTIAS.</p>
		<p>ACORDAMOS QUE, NO LIMITE MÁXIMO PERMITIDO PELA LEGISLAÇÃO APLICÁVEL, NÃO SEREMOS RESPONSÁVEIS (SEJA EM TERMOS DA RESPONSABILIDADE CONTRATUAL, DA RESPONSABILIDADE CIVIL (INCLUINDO NEGLIGÊNCIA) OU OUTRA), EM NENHUMA CIRCUNSTÂNCIA, POR QUALQUER (a) INTERRUPÇÃO DE ACTIVIDADE; (b) ATRASO OU INTERRUPÇÃO NO ACESSO À APLICAÇÃO; (c) NÃO ENTREGA DE DADOS, ERRO DE ENTREGA, CORRUPÇÃO, DESTRUIÇÃO OU OUTRA MODIFICAÇÃO; (d) PERDA OU DANO DE QUALQUER TIPO INCORRIDO COMO CONSEQUÊNCIA DE TRANSACÇÕES COM APLICAÇÕES WEB EXTERNAS OU COMO RESULTADO DA PRESENÇA DE LIGAÇÕES PARA A APLICAÇÃO WEB EXTERNA NA APLICAÇÃO; (e) VÍRUS INFORMÁTICO, FALHA NO SISTEMA OU ANOMALIA QUE PODERÃO OCORRER NO ÂMBITO DA UTILIZAÇÃO DA APLICAÇÃO, INCLUINDO DURANTE HIPERLIGAÇÕES PARA APLICAÇÕES WEB DE TERCEIROS OU A PARTIR DE APLICAÇÕES WEB DE TERCEIROS; (f) IMPRECISÃO OU OMISSÃO NO CONTEÚDO OU (g) EVENTO QUE ESTEJA FORA DO NOSSO CONTROLO RAZOÁVEL.</p>
		<p>ALÉM DISSO, NO LIMITE MÁXIMO PERMITIDO POR LEI, NÃO SEREMOS RESPONSÁVEIS POR QUAISQUER DANOS INDIRECTOS, ESPECIAIS, PUNITIVOS, ACIDENTAIS OU CONSEQUENCIAIS DE NENHUM TIPO (INCLUINDO PERDA DE LUCROS) RELACIONADOS COM A APLICAÇÃO OU COM A UTILIZAÇÃO DA MESMA INDEPENDENTEMENTE DO TIPO DE ACÇÃO, SEJA NOS TERMOS DA RESPONSABILIDADE CONTRATUAL, DA RESPONSABILIDADE CIVIL (INCLUINDO NEGLIGÊNCIA) OU OUTRA, MESMO QUE TENHAMOS SIDO ALERTADOS PARA A POSSIBILIDADE DE OCORRÊNCIA DOS REFERIDOS DANOS, E EM NENHUM CASO PODERÁ A NOSSA RESPONSABILIDADE MÁXIMA TOTAL EXCEDER CEM DÓLARES ($100.00).</p>
		<p>O PARTICIPANTE CONCORDA QUE NÃO PODERÁ MOVER QUALQUER ACÇÃO DECORRENTE DA UTILIZAÇÃO DA APLICAÇÃO OU DOS PRESENTES TERMOS E CONDIÇÕES, OU RELACIONADA COM A APLICAÇÃO OU OS PRESENTES TERMOS E CONDIÇÕES, MAIS DE UM (1) ANO DEPOIS DO SURGIMENTO DA CAUSA DA ACÇÃO RELACIONADA COM A REIVINDICAÇÃO.</p>

		<h3>9. Indemnização</h3>
		<p>O participante concorda defender-nos, indemnizar-nos e isentar-nos de responsabilidade em caso de perdas, danos ou custos, incluindo honorários razoáveis pagos a advogados, decorrentes de qualquer reivindicação, acção ou exigência de terceiros em resultado da utilização da aplicação por parte do participante ou de violação dos presentes termos e condições. O participante concorda ainda indemnizar-nos em caso de perdas, danos ou custos, incluindo honorários razoáveis pagos a advogados, decorrentes da utilização por parte do participante da robots de software, spiders, rastreadores ou ferramentas de recolha e extracção de dados afins, ou de qualquer outra acção tomada pelo participante que signifique um peso excessivo ou sobrecarga da nossa infra-estrutura.</p>

		<h3>10. Diferendos</h3>
		<p>No que respeita a qualquer diferendo relativamente à aplicação, todos os direitos, todas as obrigações e todas as acções contempladas pelos presente termos e condições serão regidos pela legislação de Nova Iorque, como se os termos e condições fossem um contrato plenamente celebrado e plenamente executado em Nova Iorque. Qualquer diferendo relacionado de qualquer forma com a visita à aplicação será submetido a arbitragem confidencial em Nova Iorque e o participante submete-se à respectiva jurisdição e prática processual. No entanto, na medida em que o participante tenha violado ou ameaçado violar de algum modo os nossos direitos de propriedade intelectual ou os direitos de propriedade intelectual das nossas filiais, dos nossos parceiros ou das nossas entidades licenciadoras ou, pelo contrário, tenha causa de pedir em equity, poderemos procurar medidas cominatórias ou outro remédio adequado em qualquer tribunal de jurisdição competente, concordando o participante com a jurisdição e o foro do referido tribunal para os fins referidos. A arbitragem no âmbito do presente acordo será levada a efeito nos termos das Consumer-Related Disputes Supplementary Rules (Normas Suplementares para Diferendos Relacionados com o Consumidor) em vigor na American Arbitration Association (Associação Americana de Arbitragem). A decisão arbitral é vinculativa e poderá ser equiparada a decisão judicial em qualquer tribunal de jurisdição competente. Dentro do limite máximo permitido pela lei aplicável, nenhuma arbitragem no âmbito dos presentes termos e condições poderá ser apensa a outro processo de arbitragem envolvendo qualquer outra parte submetida aos presentes termos e condições, seja através de procedimentos de arbitragem de classe ou outros.</p>

		<h3>11.	Geral</h3>
		<p>O participante confirma e concorda que os presentes termos e condições constituem o acordo completo exclusivo entre nós e o participante relativamente à utilização da aplicação por parte do participante, substituindo e regendo todas as propostas, todos os acordos e todas outras comunicações anteriores.</p>
		<p>Reservamo-nos o direito de, segundo nosso critério exclusivo, alterar os presentes termos e condições em qualquer momento, publicando as alterações na aplicação e dando indicação da referida alteração. Quaisquer mudanças entrarão em vigor imediatamente depois da publicação na aplicação e da divulgação do esclarecimento sobre as referidas mudanças. O uso continuado da aplicação por parte do participante a partir da data da alteração significa que o participante concorda com a alteração nos termos e condições. Poderemos, com ou sem aviso prévio, cessar quaisquer dos direitos conferidos pelos presentes termos e condições. O participante respeitar qualquer cessação ou outro aviso, incluindo, quando aplicável, mediante a suspensão utilização da aplicação.</p>
		<p>Não se poderá interpretar que os presentes termos e condições levarão à criação de qualquer agência, parceria, ou outra forma de iniciativa conjunta entre nós e o participante. O facto de em algum momento não exigirmos o cumprimento por parte do participante de qualquer disposição dos presentes termos e condições não afectará o nosso pleno direito de exigir o referido cumprimento em qualquer momento, e a nossa renúncia de violação de qualquer disposição dos presentes termos e condições não será interpretada ou considerada uma renúncia à própria disposição. No caso de qualquer disposição dos presentes termos e condições ser inexequível ou inválida nos termos de qualquer legislação aplicável ou ser assim considerada por qualquer sentença arbitral ou decisão judicial, a referida inexequibilidade ou invalidade não tornará os presentes termos e condições inexequíveis ou inválidos como um todo, tendo os presentes termos e condições de ser modificados, na medida do possível, pela entidade adjudicadora de forma a reflectirem plenamente a intenção original das partes na disposição original.</p>
		<p>Se tiver alguma questão relativamente aos presentes termos e condições, envie, por favor, uma mensagem de correio electrónico para consumercare-us@gcc.elc.estee.com. [INSERIR A MORADA DO MERCADO LOCAL]</p>

	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>