<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>2013 MKF KAMPANYASI: ULUSLARARASI HÜKÜM VE ŞARTLAR</h2>
		<h3>Yürürlük Tarihi: 1 Ağustos 2013</h3>

		<p><strong>The Estée Lauder Companies’in Meme Kanseri Farkındalık Kampanyası Facebook Uygulaması’na (<i>"Uygulama"</i>) Hoş geldiniz.</strong></p>
		<p>Estée Lauder Companies Inc. Uygulama’da mevcut olan içerik ve hizmetleri size, bazı işlevler, özellikler veya promosyonlar ile müşteri hizmetleri ile bağlantılı Uygulama üzerinde bulabileceğiniz ve tamamı işbu hüküm ve şartların bir parçası ve bunlara dahil olduğu kabul edilen aşağıdaki hüküm ve şartlara, politikalara ve diğer şartlar ve koşullara tabi olarak sağlamaktadır (birlikte <i><strong>“Hüküm ve Şartlar”</strong></i>). Uygulama’ya erişmek veya Uygulama’yı kullanmakla, bu Hüküm ve Şartları okuduğunuzu, anladığınızı ve bunları herhangi bir sınırlama veya çekince söz konusu olmaksızın kabul ettiğinizi tasdik ediyorsunuz.</p>

		<h3>1. Gizlilik</h3>
		<p>Gizlilik uygulamalarımızı anlayabilmek için lütfen <strong>Gizlilik Politikamız’</strong>ı inceleyeniz. </p>

		<h3>2. Fikri Mülkiyet</h3>
		<p>Facebook, Inc. tarafından kendi platformunun kullanımına ilişkin olarak sağlanan herhangi bir bilgi ve/veya içerik hariç olmak üzere, ticari markalar, logolar, hizmet markaları, metinler, grafikler, logolar, buton ikonları, resimler, ses klipleri, veri derlemeleri ve yazılımlar ve bunların derleme ve düzenlemeleri de dahil olmak ancak bunlarla sınırlı olmamak üzere başkaca bir şekilde Uygulama’da yer alan tüm bilgi ve içerikler ve bunların “görüntü ve hissiyatı” (birlikte <i><strong>“İçerik”</strong></i>) The Estée Lauder Companies Inc.’in, bağlı kuruluşlarımız, ortaklarımız veya lisans verenlerimizin mülkiyetinde olup, bunlar, telif hakları ve markalara ilişkin kanunlar da dahil olmak üzere Amerika Birleşik Devletleri kanunları ve uluslararası kanunlar tarafından korunmaktadır.</p>
		<p><strong>Madde 3</strong>’teki sınırlı lisanslarda belirtilen veya tabi olunan hukuk çerçevesinde zorunlu olan haller dışında, ne İçerik ne de Uygulama’nın herhangi bir kısmı, kısmen veya tamamen, açık ön yazılı rızamız olmadan herhangi bir amaç için kullanılamaz, yeniden üretilemez, çoğaltılamaz, kopyalanamaz, satılamaz, yeniden satılamaz, erişim sağlanamaz, değiştirilemez veya başkaca bir şekilde istifade edilemez. </p>

		<h3>3. Sınırlı Lisanslar</h3>
		<p>Size, Uygulama’ya erişmeniz ve Uygulama’yı kişisel amaçlarla kullanmanız için sınırlı, geri dönülebilir ve münhasır olmayan bir lisans veriyoruz. Bu sınırlı lisans: (a) Uygulama’yı veya herhangi bir parçasını kapatmak için çerçeveleme veya çerçeveleme teknikleri kullanma; (b) Uygulama’yı veya herhangi bir ve/veya bütün İçerik’i yeniden yayınlama, yeniden dağıtma, iletme, satma, lisans verme veya indirme (ön belleğe alma veya Uygulama’yı görüntülemek için gerekli olan haller dışında); (c) Uygulama’yı veya herhangi bir ve/veya bütün İçerik’i kişisel kullanım dışında herhangi bir şekilde kullanma; (d) Uygulama’ya veya herhangi bir ve/veya bütün İçerik’e dayanarak herhangi bir türev işi değiştirme, ters mühendisliğe tabi tutma veya yaratma; (e) kendiniz veya herhangi bir taraf yararına hesap bilgilerini toplama; (f) herhangi bir meta tag’leri veya herhangi bir ve/veya bütün İçerik’i kullanan herhangi başkaca “gizli metni” kullanma; veya (g) yazılım robotları, örümcekler, ağ gezginleri veya benzeri veri toparlama ve ayrıştırma araçlarını kullanma veya altyapımıza makul olmayan bir külfet yaratabilecek veya yükleyebilecek herhangi başkaca bir işlem yapma haklarını kapsamaz. Uygulama’yı veya Uygulama’ya konulan veya Uygulama’da yer alan tüm tescil bildirimlerini değiştirmeden tutmalısınız.</p>
		<p>Uygulama’yı veya herhangi bir ve/veya bütün İçeriğimiz’in tarafınızca herhangi bir izinsiz kullanımı, tabi olunan hukuk veya işbu Hüküm ve Şartlar’da sağlanan herhangi başkaca bir telafiye halel getirmeksizin, işbu <strong>Madde 3</strong>’te verilen sınırlı lisansı kendiliğinden sona erdirecektir.</p>

		<h3>4. Yükümlülükleriniz ve Sorumluluklarınız</h4>
		<p>Uygulama’ya erişim veya Uygulama’nın kullanımında, işbu Hüküm ve Şartlar’a ve erişim ve kullanıma ilişkin olarak Uygulama’da yayınlanan özel uyarı ve talimatlara uyacaksınız. Her zaman hukuk, örf adet ve iyi niyet çerçevesinde hareket edeceksiniz. Uygulama’da veya herhangi bir İçerik’te veya Uygulama’da görünebilen hizmetlerde herhangi bir değişiklik veya tadilat yapamaz ve Uygulama’nın bütünlüğüne ve işleyişine herhangi bir şekilde zarar veremezsiniz. İşbu Hüküm ve Şartlar’ın herhangi başkaca bir hükmünün genelliğine sınırlama getirmeksizin, işbu Hüküm ve Şartlar’da belirtilen yükümlülüklerinizden herhangi birisi bakımından ihmal ile veya kasten temerrüde düşmeniz halinde, bunun The Estée Lauder Companies’e, bağlı kuruluşları, ortakları veya lisans verenleri nezdinde sebep olabileceği tüm zarar ve ziyanlardan sorumlu olacaksınız.</p>

		<h3>5. Üçüncü Kişi Bağlantıları</h3>
		<p>Web sitesi dışındaki herhangi bir sayfanın içeriğinden veya Uygulama’ya veya Uygulama’dan bağlantılı olan herhangi başkaca web sitelerinden sorumlu değiliz. Uygulama’da görünen bağlantılar yalnızca kolaylık sağlama amaçlı olup, bunlar, bizim veya bağlı kuruluşlarımızın veya ortaklarımızın atıf yapılan içeriği, ürünü, hizmeti veya tedarikçiyi onayladığımız anlamına gelmez. Web sitesi dışındaki herhangi bir sayfadan veya diğer web sitelerinden veya web sitelerine yaptığınız bağlantıların riski tamamen size aittir. Bunları incelemekten veya değerlendirmekten hiçbir şekilde sorumlu değiliz, ve Uygulama’da veya Uygulama’dan web sitesi dışındaki sayfalara veya diğer web sitelerine sağlanan bağlantıların tekliflerini garanti etmiyoruz veya bunların gizlilik politikaları ve hüküm ve şartları da dahil olmak ancak bunlarla sınırlı olmamak üzere, söz konusu sayfaların ve web sitelerinin işlemleri, içeriği, ürünleri veya hizmetleri ile ilgili herhangi bir sorumluluk veya yükümlülük almıyoruz. Ziyaret ettiğiniz tüm web sitesi dışındaki sayfaların ve diğer web sitelerinin hüküm ve şartları ve gizlilik politikalarını dikkatlice incelemelisiniz.</p>

		<h3>6. Kullanıcı İçeriği</h3>
		<p>Uygulama’ya veri, metin, yazılım, müzik, ses, fotoğraf, grafik, görüntü, video, mesaj veya başkaca malzemeler (<i><strong>“Kullanıcı İçeriği”</strong></i>) ilettiğinizde, yüklediğinizde, koyduğunuzda, e-posta ile gönderdiğinizde veya başkaca bir şekilde sağladığınızda, söz konusu Kullanıcı İçeriği’nden tamamen sorumlu olursunuz. Politikamız gereği, istenmeden verilen tavsiye ve fikirleri reddediyoruz. İstenmeden verilen tavsiye ve fikirlere ilişkin politikamıza bakılmaksızın, tarafımıza sağladığınız herhangi bir soru, geri bildirim, öneriler, fikirler veya diğer bilgiler (birlikte, <i><strong>"Sunumlar"</strong></i>) tescilli veya gizli değilmiş gibi muamele görecektir. Ayrıca, Sunumlarınız’ın iade edilmeyeceğini ve Sunumlarınız’ı ve bunlarda yer alan herhangi bir fikir, konsept veya know-how’u, herhangi bir ödeme veya herhangi başka bir şekilde karşılık söz konusu olmaksızın, ürünlerin geliştirilmesi, imalatı, dağıtımı ve pazarlaması da dahil olmak ancak bunlarla sınırlı olmamak üzere herhangi bir amaçla kullanabileceğimizi tasdik etmektesiniz.</p>
		<p><strong>Gizlilik Politikası</strong>’nın şartlarına tabi olmak üzere, herhangi bir Kullanıcı İçeriği’ni iletmek veya yayınlamakla, işbu belge ile bizlere, herhangi bir Kullanıcı İçeriği’ni tamamen veya kısmen kopyalama, bunlardan türev işler elde etme, bunları şu anda bilinen veya bundan sonra geliştirilecek olan herhangi bir şekilde, ortamda veya teknoloji ile, ister tek başına ister diğer işlerin bir parçası olarak dağıtma veya gösterme ve Kullanıcı İçeriği’ni kendi ürün ve hizmetlerimiz içerisinde veya bunlarla bağlantılı olarak kullanma da dahil olmak ve fakat bunlarla sınırlı olmaksızın, Kullanıcı İçeriği’ni uygun gördüğümüz herhangi bir şekilde kopyalama, kullanma, çoğaltma, değiştirme, adapte etme, tercüme etme, yayınlama, lisans verme, dağıtma, satma veya temlik etmeye ilişkin münhasır olmayan, devredilebilen, alt lisansa konu olabilen, royaltisiz dünya çapında bir lisans veriyorsunuz. Ayrıca, işbu belge ile bizlere, adınız, görüntünüzü ve benzerlerinizi, Kullanıcı İçeriğiniz için uygun gördüğümüz herhangi bir şekilde herhangi bir amaçla kullanma hakkını da veriyorsunuz.</p>
		<p>Biz değil, tüm üçüncü kişiler Uygulama’da yayınladıkları tüm Kullanıcı İçeriği’nden tamamen sorumludur. (a) Hukuka aykırı, zararlı, tehditkar, istismar edici, taciz eden, işkence edici, aşağılayıcı, terbiyesiz, müstehcen, pornografik, hakaret edici, başkalarının gizliliğine müdahale eden, nefret dolu veya ırk ve etnik köken açısından veya başkaca bir şekilde sakıncalı olan; (b) herhangi bir kanun çerçevesinde veya sözleşme veya vekalet ilişkileri çerçevesinde verme yetkisini haiz olmadığınız; (c) yanlış, hatalı veya yanıltıcı olduğunu bildiğiniz; (d) herhangi bir üçüncü kişi tarafından karşılığında tazmin edildiğiniz veya herhangi bir karşılık verildiğiniz; veya (e) herhangi bir tarafın herhangi bir patent, marka, ticari sır, telif hakkı veya başkaca tescilli haklarını ihlal eden Kullanıcı İçeriği’nin iletilmesi, yüklenmesi, yayınlanması, e-posta ile gönderilmesi veya başkaca bir şekilde Uygulama’ya alınması ile iştigal etmeyeceğinizi veya başkalarının bunlarla iştigal etmesine destek olmayacağınızı veya teşvik etmeyeceğinizi kabul ediyorsunuz. Ayrıca, zincir mektuplar, toplu postalar veya herhangi bir türden “spam” de dahil olmak üzere herhangi bir yazılım virüsü, talep edilmeyen veya izin verilmeyen reklam, istek veya promosyon malzemesini iletmemeyi, yüklememeyi, yayınlamamayı, e-posta ile göndermemeyi veya başkaca bir şekilde sağlamamayı da kabul ediyorsunuz. Ayrıca, (i) herhangi bir kişi veya kuruluşu taklit etmemeyi veya herhangi bir kişi veya kuruluşla bağlantınızı yanlış bir şekilde beyan etmemeyi veya başkaca bir şekilde yanlış tanıtmamayı; (ii) herhangi bir şekilde küçüklere zarar verilmesi de dahil olmak üzere herhangi bir üçüncü kişiyi, başkasının taciz edilmesinin savunulması da dahil olmak üzere, “gizlice takip etmemeyi” veya başkaca bir şekilde taciz etmemeyi; (iii) herhangi bir Kullanıcı İçeriği’nin menşeini saklamak için üstbilgileri taklit etmemeyi veya tanımlayıcıları başkaca bir şekilde manipüle etmemeyi; (iv) kasten veya kasıtsız olarak herhangi bir tabi olunan yerel, eyalet, ulusal veya uluslararası kanunu ihlal etmemeyi; veya (v) diğer kullanıcılar hakkında kişisel kimlik bilgilerini toplamamayı veya depolamamayı da kabul ediyorsunuz.</p>

		<p>Uygulama’ya iletilen veya Uygulama’ya konulan Kullanıcı İçeriği’ni onaylamıyoruz veya kontrol etmiyoruz, ve bu nedenle, Kullanıcı İçeriği’nin doğruluğunu, bütünlüğünü veya kalitesini garanti etmiyoruz. Uygulama’yı kullanarak, size saldırgan, uygunsuz veya sakıncalı gelebilecek Kullanıcı İçeriği’ne maruz kalabileceğinizi anlıyorsunuz. Hiçbir durumda, herhangi bir Kullanıcı İçeriği’ndeki herhangi bir hata veya eksiklik veya iletilen, yüklenen, yayınlanan, e-posta ile gönderilen veya Uygulama aracılığıyla başkaca bir şekilde sağlanan herhangi bir Kullanıcı İçeriği’nin kullanımı neticesinde tarafınızca katlanılan herhangi bir türden zarar veya ziyan da dahil olmak ancak bunlarla sınırlı olmamak üzere, herhangi bir Kullanıcı İçeriği’nin herhangi bir şekilde kullanımından sorumlu olmayacağız.</p>
		<p>Hiçbir şekilde tarafınızın ve Güç Çevreniz’in iştigal etmeye karar verdiği İşlemler’i incelemek veya değerlendirmekten hiçbir şekilde sorumlu olmadığımız gibi, İşleminiz’i veya Güç Çevrenizi tasdik etmek yükümlülüğü altında da değiliz. İşleminiz’in seçimi veya tamamlanması veya tarafınız veya Güç Çevreniz’deki herhangi birisi tarafından İşlem’in tamamlanamamasına ilişkin herhangi bir sorumluluk veya yükümlülük kabul etmiyoruz.</p>
		<p>Münhasıran kendi takdirimiz doğrultusunda, herhangi bir Kullanıcı İçeriği’ni yayınlamayı reddetme veya kaldırma hakkını (ancak yükümlülüğünü değil) haiz olduğumuzu ve herhangi bir Kullanıcı İçeriği’ni değiştirme, sıkıştırma veya silme hakkını saklı tuttuğumuzu tasdik ediyorsunuz. Yukarıdaki hükmün veya işbu Hüküm ve Şartlar’ın herhangi başka bir hükmünün genelliğine sınırlama getirmeksizin, işbu Hüküm ve Şartlar’ı ihlal eden veya başkaca bir şekilde sakıncalı olan herhangi bir Kullanıcı İçeriği’ni kaldırma hakkına sahip bulunuyoruz ve işbu Hüküm ve Şartları ihlal eden veya başkalarının haklarını zedeleyen herhangi bir kullanıcıya ön bildirimde bulunmaksızın hizmet vermeyi reddetme hakkını saklı tutuyoruz.</p>

		<h3>7. Telif Haklarına ilişkin Şikayetler</h3>
		<p>Başkalarının fikri mülkiyet haklarına saygı duyuyoruz. Telif hakkına tabi malzemelerin telif hakkının ihlalini teşkil edecek şekilde kopyalandığına inanıyorsanız lütfen Atanmış Vekilimiz’e ihlali bildirmek üzere e-posta veya yazılı bildirim gönderiniz ve aşağıda belirtilenleri sağlayınız: (i) ihlal edildiğini ileri sürdüğünüz telif hakkına sahip iş(ler)in tanımı ve telif hakkı sahibi olduğunuza veya telif hakkı sahibi adına hareket etmeye yetkili olduğunuza dair teyit; (ii) ihlal ettiğini iddia ettiğiniz malzemenin tarifi ve söz konusu malzemenin Uygulama’daki yeri; (iii) adresiniz, telefon numaranız ve e-posta adresiniz.</p>
		<p>Telif hakkı ihlallerine ilişkin talep bildirimleri için Atanmış Vekilimiz; Üst Düzey Başkan Vekili ve Baş Hukuk Müşaviri Vekili Gregg Marrazzo The Estée Lauder Companies Inc., 767 Fifth Avenue, New York, N.Y. 10153. Telefon: (212) 277-2320. E-posta: gmarrazz@estee.com.</p>
		<p><strong>AÇIKLAMA: YUKARIDA YER ALAN İRTİBAT BİLGİLERİ MÜNHASIRAN AVEDA’YA TELİF HAKKI SAHİBİ MALZEMELERİN İHLAL EDİLMİŞ OLABİLECEĞİNE DAİR BİLDİRİMDE BULUNULMASI İÇİN VERİLMİŞTİR. TÜM DİĞER SORULARINIZ BURADAN CEVAPLANMAYACAK OLUP, BUNLAR consumercare-us@gcc.elc.estee.com. ADRESİNDEN MÜŞTERİ HİZMETLERİ GRUBUMUZA YÖNLENDİRİLMELİDİRLER.</strong></p>

		<h3>8. Beyan ve Garantiler; Sorumluluğun Sınırlandırılması</h3>
		<p>BU UYGULAMA “OLDUĞU GİBİ” SUNULMAKTADIR. İŞBU HÜKÜM VE ŞARTLAR VEYA SİTE İLE BAĞLANTILI OLARAK, SÖZ KONUSU BEYAN VE GARANTİLERİN HUKUKEN HARİÇ TUTULABİLİR BEYAN VE GARANTİLER OLMADIĞI HALLER DIŞINDA, TİCARİ ELVERİŞLİLİK, İHLAL BULUNMAMASI VEYA BELİRLİ BİR AMACA UYGUNLUK DA DAHİL OLMAK VE FAKAT BUNLARLA SINIRLI OLMAMAK ÜZERE, HER NE OLURSA OLSUN HERHANGİ BİR TÜRDEN HİÇ BİR AÇIK VEYA ZIMNİ BEYAN VEYA GARANTİDE BULUNMAMAKTAYIZ.</p>
		<p>TABİ OLUNAN HUKUK ÇERÇEVESİNDE MÜSAADE EDİLEN EN GENİŞ ÖLÇÜDE, HERHANGİ BİR DURUMDA, HERHANGİ BİR (a) İŞTE MEYDANA GELEN AKSAKLIK; (b) SİTEYE ERİŞİMDEKİ GECİKMELER VEYA ERİŞİMDEKİ AKSAKLIKLAR; (c) VERİLERİN TESLİM EDİLMEMESİ, YANLIŞ TESLİM EDİLMESİ, BUNLARDAKİ YOLSUZLUK, TAHRİP VEYA BAŞKACA BİR DEĞİŞİKLİK; (d) UYGULAMA’DAKİ WEB UYGULAMASI DIŞINDAKİ BAĞLANTILAR İLE YAPILAN MUAMELELER VEYA BUNLARIN VARLIĞI NETİCESİNDE KATLANILAN HERHANGİ BİR TÜRDEN BİR ZARAR VEYA ZİYAN; (e) ÜÇÜNCÜ KİŞİLERİN WEB UYGULAMALARINA VEYA WEB UYGULAMALARINDAN SAĞLANAN HİPER BAĞLAR ESNASINDA OLANLAR DA DAHİL OLMAK ÜZERE SİTE’NİN KULLANIMI İLE BAĞLANTILI OLARAK MEYDANA GELEBİLECEK BİLGİSAYAR VİRÜSLERİ, SİSTEM ARIZALARI VEYA BOZUKLUKLARI; (f) İÇERİKTEKİ HERHANGİ BİR YANLIŞLIK VEYA EKSİKLİK; VEYA (g) MAKUL KONTROLÜMÜZ DIŞINDAKİ OLAYLARDAN SORUMLU VEYA YÜKÜMLÜ OLMAYACAĞIMIZI (İSTER SÖZLEŞME, İSTER HAKSIZ FİİL (İHMAL DAHİL) İSTER BAŞKACA BİR ÇERÇEVEDE) KABUL EDİYORSUNUZ.</p>
		<p>AYRICA, HUKUK ÇERÇEVESİNDE MÜSAADE EDİLEN EN GENİŞ ÖLÇÜDE, İŞLEMİN ŞEKLİNE BAKILMAKSIZIN, İSTER SÖZLEŞME, İSTER HAKSIZ FİİL (İHMAL DE DAHİL) VEYA BAŞKACA BİR ÇERÇEVEDE VE SÖZ KONUSU ZARAR İHTİMALİ HAKKINDA TARAFIMIZA GÖRÜŞ BİLDİRİLMİŞ OLSA DAHİ, UYGULAMA’YA VEYA UYGULAMA’YI KULLANIMINIZA İLİŞKİN HERHANGİ BİR TÜRDEN HERHANGİ BİR DOĞRUDAN, ÖZEL, CEZAİ, ARIZİ VEYA NETİCESEL ZARARLARDAN (KAR KAYIPLARI DA DAHİL) DA SORUMLU OLMAYACAĞIZ VE HİÇBİR DURUMDA AZAMİ TOPLAM SORUMLULUĞUMUZ YÜZ BİN DOLARI (100.000 $)’NI AŞMAYACAKTIR.</p>
		<p>UYGULAMA’NIN KULLANIMI VEYA İŞBU HÜKÜM VE ŞARTLAR’DAN KAYNAKLANAN VEYA BUNLARLA İLGİLİ HİÇBİR İDDİA VEYA DAVANIN, SÖZ KONUSU İDDİA VEYA DAVA SEBEBİNİN ORTAYA ÇIKMASINDAN İTİBAREN BİR (1) YIL SONRA İLERİ SÜRÜLEMEYECEĞİNİ KABUL EDİYORSUNUZ.</p>

		<h3>9. Tazminat</h3>
		<p>Bizi, Uygulama’yı kullanımınız veya işbu Hüküm ve Şartlar’ı ihlalinizden kaynaklanan herhangi bir üçüncü kişiye ait iddia, dava veya talep neticesinde ortaya çıkan makul avukatlık ücretleri de dahil olmak üzere herhangi bir zarar, ziyan veya masrafa karşı savunmayı, tazmin etmeyi ve bunlardan zarar görmememizi sağlamayı kabul ediyorsunuz. Ayrıca, bizi, yazılım robotları, örümcekler, ağ gezginleri veya benzeri veri toparlama ve ayrıştırma araçlarını kullanımınız veya altyapımıza makul olmayan bir külfet yaratabilen herhangi başkaca bir işlem neticesinde ortaya çıkan makul avukatlık ücretleri de dahil olmak üzere herhangi bir zarar, ziyan veya masrafa karşı tazmin etmeyi de kabul ediyorsunuz.</p>

		<h3>10. Uyuşmazlıklar</h3>
		<p>Uygulama’ya ilişkin herhangi bir uyuşmazlık ile ilgili olarak, tüm haklar ve yükümlülükler ve işbu Hüküm ve Şartlar ile tasarlanan tüm işlemler, sanki Hüküm ve Şartlar tamamen New York’ta akdedilen ve ifa edilen bir sözleşmeymiş gibi New York kanunlarına tabi olacaktır. Herhangi bir şekilde Uygulama’yı kullanımınıza ilişkin herhangi bir uyuşmazlık, New York’ta gizli tahkime sunulacak olup, siz de bunların yargılama yetkisini ve muamelelerini kabul ediyorsunuz; ancak şöyle ki, fikri mülkiyet haklarımızı veya bağlı kuruluşlarımız, ortaklarımız veya lisans verenlerimizin fikri mülkiyet haklarını herhangi bir şekilde ihlal ettiğiniz veya ihlal etme tehdidinde bulunduğunuz veya başkaca bir şekilde hakkaniyet çerçevesinde bir dava sebebine sahip olduğumuz takdirde, yetkili yargı çevresindeki herhangi bir mahkeme nezdinde ihtiyati tedbir veya diğer uygun telafileri almaya çalışabiliriz ve siz de söz konusu amaçlar bakımından söz konusu herhangi bir mahkemenin yargılama yetkisi ve görevine rıza göstermektesiniz. İşbu Sözleşme çerçevesindeki tahkim o esnada Amerikan Tahkim Birliği tarafından yürürlükte olan Tüketici ile İlgili Uyuşmazlıklara İlişkin Ek Kurallar’a göre yürütülecektir. Hakem kararı bağlayıcı olacak ve yetkili yargı dairesindeki herhangi bir mahkeme tarafından hüküm olarak icra edilecektir. Tabi olunan hukuk tarafından müsaade edilen en geniş ölçüde, işbu Hüküm ve Şartlar çerçevesindeki hiçbir tahkim işbu Hüküm ve Şartlar’a tabi olan herhangi başka bir tarafın tahkimi ile, ister toplu tahkim muamelesi olarak ister başkaca bir şekilde birleştirilmeyecektir.</p>

		<h3>11.	Genel Hükümler</h3>
		<p>İşbu Hüküm ve Şartlar’ın, Uygulama’yı kullanımınıza dair aramızdaki tam ve münhasır anlaşmayı teşkil ettiğini ve bundan önceki tüm teklif, anlaşma veya diğer haberleşmelerin yerine geçtiğini ve bunlardan üstün geldiğini tasdik ve kabul ediyorsunuz. </p>
		<p>Münhasıran kendi takdirimiz doğrultusunda, işbu Hüküm ve Şartlar’ı, değişiklikleri Uygulama’da yayınlamak ve söz konusu değişikliğe ilişkin bildirimde bulunmak suretiyle herhangi bir zamanda değiştirme hakkını saklı tutuyoruz. Herhangi bir değişiklik, Uygulama’da yayınlanmasının ve söz konusu değişikliğe ilişkin bildirimin çıkartılmasının hemen ardından yürürlüğe girer. Bundan sonra Uygulama’yı kullanmaya devam etmeniz, değiştirilen tüm söz konusu Hüküm ve Şartlar’a ilişkin kabulünüzü teşkil eder. Önceden bildirimde bulunarak veya bulunmadan, işbu Hüküm ve Şartlar ile verilen haklardan herhangi birisini feshedebiliriz. Duruma göre, Uygulama’nın tüm kullanımlarına son vermek de dahil olmak üzere, herhangi bir fesih veya başkaca bir bildirime derhal uyacaksınız.</p>
		<p>İşbu Hüküm ve Şartlar’da yer alan hiçbir husus, aramızda herhangi bir acentelik, ortaklık veya başkaca bir ortak işletme şekli yaratıyormuş gibi yorumlanmayacaktır. İşbu belgenin herhangi bir hükmünü ifa etmenizi talep etmememiz, bundan sonra herhangi bir zamanda söz konusu ifayı talep etmemize ilişkin hakkın tamamını etkilemeyecek olduğu gibi, herhangi bir hükmün ihlaline ilişkin bir feragat, hükmün kendisinin feragat olarak ele alınmayacak veya böyle sayılmayacaktır. İşbu Hüküm ve Şartlar’ın herhangi bir hükmünün herhangi bir tabi olunan hukuk çerçevesinde bundan böyle icra edilemez veya geçersiz hale gelmesi veya herhangi bir tabi olunan hakem kararı veya mahkeme hükmü ile böyle ilan edilmesi durumunda, söz konusu icra edilemezlik veya geçersizlik durumu, işbu Hüküm ve Şartlar’ı bir bütün olarak icra edilemez veya geçersiz hale getirmeyecek, ancak bu işbu Hüküm ve Şartlar, yargılama mercii tarafından mümkün mertebe, tarafların orijinal hükümde yansıtılan asıl niyetlerini en iyi şekilde yansıtacak şekilde değiştirileceklerdir.</p>
		<p>İşbu Hüküm ve Şartlar ile ilgili herhangi bir sorunuz olduğunda lütfen bize consumercare-us@gcc.elc.estee.com adresinden e-posta gönderiniz.</p>
	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>