<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>KAMPAGNE BEWUSSTSEIN FÜR BRUSTKREBS 2013 : NUTZUNGSBE-DINGUNGEN</h2>
		<h3>Datum des Inkrafttretens: 1. September 2013</h3>

		<p>Willkommen auf der Website "Bewusstsein für Brustkrebs" von ELC Deutschland Online (im Folgenden „die Website“)</p>
		<p>Die von ELC Deutschland Online (ELC Deutschland Online ist eine Abteilung der Estée Lauder Companies GmbH, Domagkstraße 10, 80807 München, Deutschland) auf der Website angebotenen Inhalte und Services unterliegen den folgenden Nutzungsbedingungen, unseren Datenschutzrichtlinien, sowie weiteren Vorgaben und Richtlinien, die an verschiedenen Stel-len unserer Website im Zusammenhang mit bestimmten Funktionen, Merkmalen, Werbeakti-onen oder Kundenserviceleistungen möglicherweise genannt werden. Alle diese Bedingungen und Richtlinien gelten als integrale Bestandteile der vorliegenden Nutzungsbedingungen (zu-sammenfassend <strong>„Nutzungsbedingungen“</strong> genannt). Durch den Zugriff auf diese Website oder durch deren Nutzung erklären Sie sich mit den vorliegenden Nutzungsbedingungen ein-verstanden.</p>

		<h3>1. Richtigkeit der Angaben</h3>
		<p>Wir sind bestrebt, unsere Produkte auf der Website möglichst genau zu beschreiben. Wir ga-rantieren jedoch nicht, dass der Website verfügbaren Inhalte präzise, zuverlässig, aktuell oder fehlerfrei sind. Ihre gesetzlichen Rechte bleiben selbstverständlich unberührt.</p>

		<h3>2. Gewerbliche Schutz- und Urheberrechte</h3>
		<p>Alle auf der Website verfügbaren Informationen und Inhalte sowie deren Design, insbesonde-re Logos, Marken, Texte, Grafiken, Schaltflächensymbole, Audioclips, Datenkompilationen und Software sowie deren Zusammenstellung und Anordnung (zusammenfassend <strong>„die Inhal-te“</strong> genannt), sind das Eigentum von ELC Deutschland Online, unseren verbundenen Unter-nehmen, Partnern oder Lizenzgebern und sind nach deutschem, US-amerikanischem und in-ternationalem Recht, insbesondere nach dem Urheber- und Markenrecht, geschützt.</p>
		<p>Die Inhalte oder Teile der Website dürfen nicht ohne unsere ausdrückliche schriftliche vorhe-rige Genehmigung, weder als Ganzes noch in Teilen und ungeachtet des Zwecks, genutzt, reproduziert, dupliziert, kopiert, verkauft, weiterverkauft, aufgerufen, verändert oder auf an-dere Weise ausgenutzt werden, außer soweit dies für die eingeschränkten Nutzungsrechte in Abschnitt 3 darlegt ist oder soweit dies nach geltendem Recht erforderlich ist.</p>

		<h3>3. Eingeschränkte Nutzungsrechte</h3>
		<p>Wir gewähren Ihnen das eingeschränkte, widerrufliche, nicht ausschließliche Recht, auf die Website zuzugreifen und diese für persönliche Zwecke zu nutzen. Dieses eingeschränkte Recht umfasst nicht die Berechtigung, a.) die Website oder Teile derselben in Frames oder mithilfe von Frame-Techniken eingebettet darzustellen; b.) die Website und/oder Inhalte der Website weiter zu veröffentlichen, weiter zu verteilen, zu übertragen, zu verkaufen, zu lizen-zieren oder herunterzuladen (außer für die Cache-Speicherung oder soweit dies für die Dar-stellung der Website erforderlich ist); c.) die Website und/oder Inhalte der Website zu anderen als rein persönlichen Zwecken zu nutzen; d.) die Website und/oder Inhalte der Website zu modifizieren, per Reverse Engineering zu verarbeiten oder von der Website und/oder von Inhalten der Website abgeleitete Werke zu schaffen; e.) Account-Informationen zum eigenen Nutzen oder zum Nutzen Dritter zu erfassen; f.) Meta-Tags oder anderen „versteckten Text“ unter Nutzung von Inhalten der Website zu verwenden, oder g.) softwaretechnische Robots, Spiders, Crawlers oder ähnliche Tools zur Datenerfassung und -extraktion zu nutzen oder andere Maßnahmen zu ergreifen, die eine unverhältnismäßige Belastung unserer Infrastruktur nach sich ziehen könnten. Sie sind verpflichtet, alle Urheberrechtshinweise, die sich auf der Website befinden, an der Website angebracht oder in ihr integriert sind, ohne Änderungen beizubehalten.</p>
		<p>Wir gewähren Ihnen außerdem das eingeschränkte, widerrufliche, nicht ausschließliche Recht, ausschließlich für persönliche, nicht gewerbliche Zwecke einen Hyperlink auf die Startseite der Website zu erstellen. Eine Website, die unsere Website verlinkt, (i.) darf per Link auf unsere Inhalte verweisen, diese aber nicht replizieren; (ii.) darf nicht besagen, dass wir eine solche Website oder die auf ihr dargestellten Dienstleistungen oder Produkte empfeh-len; (iii.) darf ihre Beziehung zu uns nicht falsch darstellen; (iv.) darf keine Inhalte enthalten, die als geschmacklos, obszön, anstößig, illegal oder für irgendeine Altersstufe ungeeignet ausgelegt werden könnten; (v.) darf uns oder unsere Produkte oder Dienstleistungen nicht auf falsche, irreführende, herabsetzende oder anderweitig anstößige oder zu beanstandende Weise darstellen oder uns mit unerwünschten Produkten, Dienstleistungen oder Meinungen in Ver-bindung bringen; und (vi.) darf ausschließlich die Startseite unserer Website, nicht aber ande-re Seiten verlinken. Wir sind berechtigt, Sie nach unserem eigenen Ermessen aufzufordern, Links zu unserer Website zu entfernen. Nach Empfang einer solchen Aufforderung sind Sie verpflichtet, die betreffenden Links unverzüglich zu entfernen und die künftige Anbringung von Links zu unterlassen, es sei denn, die erneute Anbringung von Links wurde von uns ge-sondert und ausdrücklich schriftlich genehmigt.</p>
		<p>Jegliche unbefugte Nutzung der Website und der Inhalte der Website durch Sie führt automa-tisch zum Erlöschen der vorstehend genannten eingeschränkten Rechte, unbeschadet anderer nach geltendem Recht oder nach diesen Nutzungsbedingungen bestehender Ansprüche.</p>

		<h3>4. Ihre Verpflichtungen und Verantwortlichkeiten</h4>
		<p>Beim Zugriff auf die Website oder bei der Nutzung der Website verpflichten Sie sich, die vorliegenden Nutzungsbedingungen und die besonderen Warnungen und Anweisungen zum Zugriff oder zur Nutzung zu beachten, die auf dieser Website veröffentlicht wurden. Sie sind nicht berechtigt, Änderungen oder Modifikationen an der Website, an Inhalten oder Dienst-leistungen vorzunehmen, die auf dieser Website angeboten werden. Es ist Ihnen untersagt, die Integrität oder die Funktion der Website in irgendeiner Weise zu beeinträchtigen. Ungeachtet der Gültigkeit anderer Bestimmungen der vorliegenden Nutzungsbedingungen gilt Folgendes: Wenn Sie fahrlässig oder mutwillig gegen Bestimmungen der vorliegenden Nutzungsbedin-gungen verstoßen, haften Sie für alle etwaigen Verluste und Schäden, die ELC Deutschland Online, unseren verbundenen Unternehmen, Partner oder Lizenzgeber dadurch erleiden.</p>

		<h3>5. Links zu Dritten</h3>
		<p>Wir sind nicht für Inhalte auf Seiten anderer Websites oder auf anderen Websites verantwort-lich, die auf der Website verlinkt sind oder die die Website verlinken. Auf der Website ange-zeigte Links werden nur aus Gründen der Zweckmäßigkeit bereitgestellt. Sie stellen keine Empfehlung der verlinkten Inhalte, Produkte, Dienstleistungen oder Anbieter unsererseits oder von Seiten unserer Tochtergesellschaften oder Partner dar. Wenn Sie Links zu oder von Seiten anderer Websites nutzen, geschieht dies auf eigene Gefahr. Wir sind in keiner Weise dafür verantwortlich, Seiten anderer Websites oder andere Websites zu untersuchen und zu prüfen, die auf der Website verlinkt sind oder die die Website verlinken. Auch übernehmen wir keinerlei Verantwortung oder Haftung für die Handlungen, Inhalte, Produkte oder Dienst-leistungen solcher Seiten und Websites, insbesondere auch nicht für deren Datenschutzrichtli-nien und Nutzungsbedingungen. Sie sollten die Nutzungsbedingungen und Datenschutzricht-linien aller Seiten anderer Websites prüfen, die Sie nutzen.</p>

		<h3>6. Einsendungen</h3>
		<p>Es ist unser Grundsatz, unverlangt eingesendete Empfehlungen und Ideen abzulehnen. Unge-achtet unseres Grundsatzes bezüglich unverlangt eingesendeter Empfehlungen und Ideen werden etwaige Anfragen, Rückmeldungen, Empfehlungen, Ideen oder andere Informationen, die Sie uns zur Verfügung stellen (zusammenfassend <strong>„Einsendungen“</strong> genannt), nicht ver-traulich behandelt. Es besteht kein Anspruch auf Rücksendung.</p>

		<h3>7. Inhalte von Benutzern</h3>
		<p>Wenn Sie Daten, Text, Software, Musik, Klänge, Fotografien, Grafiken, Bilder, Videos, Nachrichten oder andere Materialien („Inhalte von Benutzern“) übertragen, hochladen, ver-öffentlichen, per E-Mail einsenden oder auf andere Weise auf der Website zur Verfügung stellen, tragen Sie die ausschließliche Verantwortung für derartige Inhalte von Benutzern. In jedem Fall tragen Dritte, nicht wir, die ausschließliche Verantwortung für derartige Inhalte von Benutzern , die diese auf der Website veröffentlichen. Sie stimmen zu, dass Sie andere nicht beauftragen, unterstützen oder auffordern, Inhalte von Benutzern zu übertragen, hochzu-laden, zu veröffentlichen, per E-Mail einzusenden oder auf andere Weise auf der Website zur Verfügung zu stellen, a.) die ungesetzlich, schädlich, bedrohlich, missbräuchlich, belästigend, unerlaubt, diffamierend, vulgär, obszön, pornografisch, verleumderisch, hasserfüllt, aus ethni-schen oder anderen Gründen zu beanstanden sind oder die Datenschutzrechte anderer verlet-zen; b.) die Sie kraft Gesetzes oder bedingt durch Vertrags- oder Treuhänderverhältnisse nicht berechtigt sind, zur Verfügung zu stellen; c.) von denen Sie wissen, dass diese falsch, nicht korrekt oder irreführend sind; d.) für die Sie von Dritten entschädigt wurden oder Zuwendun-gen erhalten haben; oder e.) die gegen Patent-, Marken- Urheberrechte oder andere geistige Eigentumsrechte Dritter verstoßen oder Betriebsgeheimnisse Dritter sind. Zudem stimmen Sie zu, keine Softwareviren, keine unverlangten oder nicht genehmigten Werbe- oder Marke-tingmaterialien wie etwa Kettenbriefe, Massensendungen oder irgendeine Form von „Spam“ zu übertragen, hochzuladen, zu veröffentlichen, per E-Mail einzusenden oder auf andere Wei-se zur Verfügung zu stellen. Ferner verpflichten Sie sich, i.) sich nicht als eine andere Person oder Organisation auszugeben und Ihre Zugehörigkeit zu einer anderen Person oder Organisa-tion nicht fälschlicherweise zu behaupten oder auf andere Weise falsch darzustellen; ii.) Dritte nicht zu „stalken“ oder auf andere Weise zu belästigen, insbesondere auch die Belästigung anderer nicht gutzuheißen, Dritte nicht in irgendeiner Weise zu etwas zu verleiten oder zu schädigen, Minderjährige nicht in irgendeiner Weise zu schädigen; iii.) Briefköpfe nicht zu fälschen bzw. Kennzeichen nicht auf andere Weise zu manipulieren, so dass der Ursprung von Inhalten von Benutzern verschleiert wird; iv.) nicht absichtlich oder unabsichtlich gegen gel-tende regionale Gesetze, Landesgesetze, nationale oder internationale Gesetze zu verstoßen; und v.) keine personenbezogenen Daten über andere Benutzer zu sammeln.</p>
		<p>Wir heißen die Inhalte von Benutzern, die auf der Website übertragen oder veröffentlicht werden, nicht gut und kontrollieren diese nicht. Daher garantieren wir nicht für die Richtig-keit, Rechtschaffenheit oder Qualität von Inhalten von Benutzern. Sie sind sich dessen be-wusst, dass Sie durch die Nutzung der Website möglicherweise Inhalten von Benutzern aus-gesetzt sind, die für Sie anstößig, unanständig oder zu beanstanden sind. Unter keinen Um-ständen haften wir in irgendeiner Weise für Inhalte von Benutzern, insbesondere auch nicht für Fehler oder Auslassungen in Inhalten von Benutzern, oder für etwaige Verluste und Schä-den jedweder Art, die Ihnen infolge der Nutzung von Inhalten von Benutzern entstehen, wel-che übertragen, hochgeladen, veröffentlicht, per E-Mail eingesendet oder auf andere Weise auf der Website zur Verfügung gestellt wurden.</p>
		<p>Sie stimmen zu, dass wir berechtigt, aber nicht verpflichtet sind, die Veröffentlichung von Inhalten von Benutzern abzulehnen oder diese zu entfernen. Wir behalten uns das Recht vor, Inhalte von Benutzern zu ändern, zu kürzen oder zu löschen. Ungeachtet der Allgemeingül-tigkeit anderer Bestimmungen der vorliegenden Nutzungsbedingungen sind wir berechtigt, Inhalte von Benutzern zu entfernen, die gegen die vorliegenden Nutzungsbedingungen ver-stoßen oder auf andere Weise zu beanstanden sind. Ferner behalten wir uns das Recht vor, ohne Vorankündigung Serviceleistungen zu verweigern oder Accounts von Benutzern zu schließen, wenn diese gegen die vorliegenden Nutzungsbedingungen verstoßen oder die Rechte Dritter verletzen.</p>

		<h3>8. Beschwerden über die Verletzung von Urheberrechten</h3>
		<p>Wir respektieren Schutz- und Urheberrechte Dritter. Wenn Sie der Auffassung sind, dass ur-heberrechtlich geschützte Inhalte oder Werke kopiert wurden und dadurch Urheberrechte ver-letzt wurden, klicken Sie bitte (<strong>"hyperlink"</strong> einfügen) hier, um nähere Informationen zur Meldung von Rechtsverstößen zu erhalten.</p>

		<h3>9. Zusicherungen und Gewährleistung; Haftungsausschluss</h3>
		<p>DIE WEBSITE WIRD OHNE MÄNGELGEWÄHR BEREITGESTELLT. WIR GEBEN IN BEZUG AUF DIE NUTZUNGSBEDINGUNGEN ODER DIE WEBSITE KEINERLEI AUSDRÜCKLICHE ODER STILLSCHWEIGENDE ZUSICHERUNGEN ODER GARAN-TIEN. , INSBESONDERE <strong>SCHLIESSEN WIR AUCH GARANTIEN IN BEZUG AUF</strong> MARKTGÄNGIGKEIT, NICHTVERLETZUNG VON RECHTEN ODER EIGNUNG FÜR EINEN BESTIMMTEN ZWECK AUS, SOWEIT DER AUSSCHLUSS SOLCHER ZUSI-CHERUNGEN UND GARANTIEN RECHTLICH ZULÄSSIG IST.</p>
		<p>SIE STIMMEN ZU, DASS WIR, SOWEIT DIES DAS ANWENDBARE RECHT ER-LAUBT, UNTER KEINEN UMSTÄNDEN (GLEICH AUS WELCHEM RECHTSGRUND) VERANTWORTLICH ODER HAFTBAR SIND FÜR ETWAIGE A.) BETRIEBSUNTER-BRECHUNGEN, B.) VERZÖGERUNGEN ODER UNTERBRECHUNGEN DES ZU-GANGS ZUR WEBSITE, C.) NICHTLIEFERUNGEN, FEHLLIEFERUNGEN, BESCHÄ-DIGUNGEN, ZERSTÖRUNGEN ODER SONSTIGE MODIFIKATIONEN VON DATEN, D.) VERLUSTE ODER SCHÄDEN JEDWEDER ART, DIE DURCH DIE NUTZUNG O-DER DAS VORHANDENSEIN VON LINKS ZU ANDEREN WEBSITES ENTSTEHEN, WELC HE AUF DER WEBSITE VORHANDEN SIND, E.) COMPUTERVIREN, SYS-TEMAUSFÄLLE ODER FEHLFUNKTIONEN, DIE IN VERBINDUNG MIT IHRER NUTZUNG DER WEBSITE AUFTRETEN KÖNNEN, INSBESONDERE DURCH HY-PERLINKS ZU ODER VON WEBSITES DRITTER, F.) UNGENAUIGKEITEN ODER AUSLASSUNGEN IN INHALTEN ODER G.) EREIGNISSE AUSSERHALB UNSERES ENTSCHEIDUNGS- UND EINFLUSSBEREICHES.</p>
		<p>SÄMTLICHE HAFTUNGSAUSSCHLÜSSE ERFASSEN NICHT EVTL. SCHÄDEN AN KÖRPER UND GESUNDHEIT.</p>

		<h3>10. Rechtswahl, Gerichtsstand</h3>
		<p>Für etwaige Streitfälle im Zusammenhang mit der Website oder diesen Nutzungsbedingungen gilt deutsches Recht. Gerichtsstand ist, soweit zulässig, München. </p>

		<h3>11. Allgemeines</h3>
		<p>Sie erkennen an und stimmen zu, dass die vorliegenden Nutzungsbedingungen die vollständi-ge und ausschließliche Vereinbarung zwischen Ihnen und uns hinsichtlich Ihrer Nutzung der Website darstellen und alle früheren Vorschläge, Vereinbarungen und Mitteilungen ersetzen und außer Kraft setzen.</p>
		<p>Wir behalten uns das Recht vor, die vorliegenden Nutzungsbedingungen jederzeit und nach unserem eigenen Ermessen zu ändern. Alle Änderungen treten unmittelbar mit der Veröffent-lichung der Änderungen auf der Website und der Herausgabe der Informationen über die Än-derungen in Kraft. Nutzen Sie die Website nach Inkrafttreten von Änderungen weiter, erklä-ren Sie durch Ihre fortgesetzte Nutzung Ihr Einverständnis zu allen geänderten Nutzungsbe-dingungen. Wir sind berechtigt, mit oder ohne Vorankündigung beliebige Rechte zu widerru-fen, die wir im Rahmen der vorliegenden Nutzungsbedingungen gewährt haben. Sie verpflich-ten sich, jeglichen Widerruf von Rechten bzw. jede sonstige Mitteilung einzuhalten, u. a. dadurch, dass Sie ggf. die Nutzung der Website vollständig einstellen.</p>
		<p>Die Bestimmungen der vorliegenden Nutzungsbedingungen können nicht dahin gehend aus-gelegt werden, dass dadurch eine Partnerschaft oder eine andere Form gemeinschaftlicher Unternehmungen zwischen Ihnen und uns entsteht. Falls wir es unterlassen, von Ihnen die Einhaltung etwaiger Bestimmungen der vorliegenden Nutzungsbedingungen zu fordern, be-einträchtigt dies nicht unser Recht, später jederzeit von Ihnen die Einhaltung der entsprechen-den Bestimmungen zu fordern. Ein Verzicht auf die Verfolgung einer Verletzung der Nut-zungsbedingungen kann nicht als Verzicht auf die Verfolgung späterer Verletzungen ausge-legt werden. Falls wir darauf verzichten, eine Verletzung etwaiger Bestimmungen der vorlie-genden Nutzungsbedingungen zu verfolgen, kann daraus nicht geschlossen werden, dass wir auf die betreffenden Bestimmungen selbst verzichten. Ist eine der Bestimmungen dieser Nut-zungsbedingungen unwirksam oder nichtig oder wird rechtswirksam für unwirksam oder nichtig erklärt, so wird hiervon die Wirksamkeit der Nutzungsbedingungen im Übrigen nicht berührt. </p>
		<p>Falls Sie Fragen zu den vorliegenden Nutzungsbedingungen haben, wenden Sie sich bitte per E-Mail unter ConsumerCommunications-ELGermany@estee.com an uns.</p>
		<p>Copyright © Estée Lauder Inc. Alle weltweiten Rechte vorbehalten.</p>

	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>