<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>2013 BCA CAMPAIGN: INTERNATIONAL TERMS & CONDITIONS</h2>
		<h3>Effective Date:  August 1, 2013</h3>

		<p><strong>Benvenuti nell’applicazione della campagna della  Breast Cancer Awareness di Estée Lauder(la "Applicazione").
</strong></p>
		<p>Estée Lauder  Inc. fornisce i contenuti e i servizi disponibili dell’Applicazione, che sono soggetti ai seguenti Termini e Condizioni, la nostra Politiche sulla Privacy, termini e condizioni e le politiche che si possono trovare nella nostra applicazione in relazione a determinate funzionalità, caratteristiche o promozioni così come il servizio clienti, i quali sono considerati una parte e compresi all'interno di questi termini e condizioni (collettivamente, "Termini e condizioni"). Accedendo o utilizzando l'Applicazione, si sta riconoscendo di aver letto, capito, e accettato, senza limitazioni o riserve, di essere vincolato da questi Termini e Condizioni.</p>

		<h3>1. Privacy</h3>
		<p>Si prega di rivedere prendere visione delle nostre <strong>Privacy Policy</strong> in modo da essere informati circa le modalità e finalità di trattamento applicate per la tutela della privacy.</p>

		<h3>2.	Proprietà Intellettuale</h3>
		<p>Ad eccezione di qualsiasi informazione e / o di contenuto che viene fornito da Facebook, Inc. in relazione all'uso della sua piattaforma, tutte le informazioni e il contenuto altrimenti disponibili nell’Applicazione e il suo "look and feel", compreso ma non limitato ai marchi, loghi, marchi di servizio, testo, grafica, loghi, icone, immagini, clip audio, compilazioni di dati e software, e la compilazione e l'organizzazione di queste materie (collettivamente, il "Contenuto") è di proprietà dell’azienda Estée Lauder  Inc., i nostri affiliati, partner o licenziatari, ed è protetto dalle leggi statunitensi e internazionali, comprese le leggi che regolano i diritti d'autore e marchi di fabbrica.</p>
		<p>Ad eccezione di quanto stabilito nelle licenze limitate nel punto 3, o come richiesto dalla legge applicabile, né il contenuto, né alcuna parte della domanda può essere usata, riprodotto, duplicato, copiato, venduto, rivenduto, visitato, modificati o altrimenti sfruttata, in tutto o in parte, per qualsiasi scopo senza il nostro esplicito consenso scritto.</p>

		<h3>3.	Licenze Limitate</h3>
		<p>Vi concediamo una licenza limitata, revocabile e non esclusiva per accedere e fare uso personale dell’Applicazione. Questa licenza limitata non include il diritto di: (a) ritagliare o utilizzare tecniche di ritaglio per riprodurre l'applicazione o parte di essa, (b) ripubblicare, ridistribuire, trasmettere, vendere, concedere in licenza o scaricare l'Applicazione o qualsiasi e / o tutti i Contenuti (ad eccezione di caching o se necessario per visualizzare l'applicazione), (c) fare qualsiasi uso dell'Applicazione o qualunque e / o tutti i Contenuti diversi dall'uso personale; (d) modificare, decodificare o creare altri prodotti basati sull'Applicazione o qualsiasi e / o tutti i Contenuti, (e) raccogliere informazioni relativead un account a vantaggio di se stessi o di terzi, (f) utilizzare meta tag o altro "testo nascosto" che ogni e / o tutti i Contenuti, o (g) utilizzare robot software, spider, crawler, o simili di raccolta e di strumenti di estrazione, o fare qualsiasi altra azione che potrebbe imporre un onere irragionevole o eccessivo sulla nostra infrastruttura. È necessario conservare, senza modifiche, tutte le informazioni proprietarie sull'applicazione o affisse o contenute nella domanda.</p>
		<p>Qualsiasi utilizzo non autorizzato dell'Applicazione o qualunque e / o tutti i nostri contenuti termina automaticamente le licenze limitate di cui al presente punto 3, senza pregiudizio di ogni altro rimedio previsto dalla legge applicabile o di questi Termini e Condizioni.</p>

		<h3>4. I vostri obblighi e le vostre responsabilità</h4>
		<p>Nell’ accesso o nell'utilizzo dell'Applicazione, sarà necessario attenersi a questi Termini e Condizioni e le speciali avvertenze o le istruzioni per l'accesso o l'uso postati riguardanti l'applicazione. Si deve agire sempre in conformità con la legge, uso e in buona fede. Non è possibile effettuare alcuna modifica o alterazione per l'Applicazione o qualsiasi Contenuto o servizi che possono apparire su questa applicazione e non può danneggiare in alcun modo l'integrità o il funzionamento dell'applicazione. Senza limitare la misura di qualsiasi altra disposizione di questi Termini e Condizioni, se di default per negligenza o intenzionalmente in uno qualsiasi degli obblighi di cui ai presenti Termini e Condizioni, sarete responsabile di tutte le perdite e i danni che questo può causare a Estée Lauder Companies, le nostre affiliate, partner o licenziatari.</p>

		<h3>5. Link di Parti Terze</h3>
		<p>Noi non siamo responsabili per il contenuto di pagine esterne al Sito o di altri siti web collegati all’Applicazione. Collegamenti che appaiono nell’Applicazione sono solo per comodità e non costituiscono un'approvazione da parte nostra, i nostri affiliati o dei nostri partner del contenuto di riferimento, prodotto, servizio o fornitore. Il collegamento da e verso pagine esterne al sito o ad altri siti web è a vostro rischio e pericolo. Non siamo in alcun modo responsabile dell'esame o della valutazione, e noi non garantiamo l'offerta di pagine, di fuori del Sito o altri siti web collegati o da applicazioni, né ci assumiamo alcuna responsabilità per le azioni, i contenuti, i prodotti o servizi di tali pagine e siti web, tra cui, senza limitazione, le loro politiche sulla privacy e termini e condizioni. Si consiglia di esaminare attentamente i termini e le condizioni e le politiche sulla privacy di tutte le pagine esterne al sito e altri siti web che si visitano.</p>

		<h3>6. Contenuti dell’Utente</h3>
		<p>Quando si trasmette, carica, pubblica, si mandano  e-mail o in altro modi si rendono disponibili i propri dati, testi, software, musica, suoni, fotografie, grafica, immagini, video, messaggi o altri materiali ("Contenuti dell'utente"),  all’interno dell’ applicazione, l'utente è interamente responsabile per tali Contenuti dell'utente. La nostra politica è di rifiutare i suggerimenti e idee non richieste. Nonostante la nostra politica in materia di suggerimenti e le idee non richieste, qualsiasi richiesta di informazioni, commenti, suggerimenti, idee o altre informazioni che ci vengono (complessivamente "Materiale Presentato") saranno trattati come non di proprietà e non riservati. L'utente riconosce inoltre che il Materiale non sarà restituito e si può utilizzare il Materiale Presentato dell'utente, e tutte le idee, concetti o know-how in esso contenute, senza pagamento di denaro o qualsiasi altra forma di corrispettivo, per qualsiasi scopo, incluso, senza limitazioni, lo sviluppo, la produzione, distribuzione e commercializzazione di prodotti. Osservazioni devono essere trattati come Contenuti dell’Utente.</p>
		<p>In base ai termini della nostra <strong>Politica sulla Privacy</strong>, trasmettendo o pubblicando i Contenuti dell’ utente, Lei ci concede una licenza non esclusiva trasferibile sub-licenziabile, libera da royalty, con licenza di copiare in tutto il mondo, utilizzare, riprodurre, modificare, adattare, tradurre, pubblicare, concedere in licenza, distribuire, vendere o trasferire i contenuti dell’ Utente in alcun modo, nel modo in cui riterremo opportuno, incluso ma non limitato a copiare in tutto o in parte, la creazione di opere derivate, distribuzione e visualizzazione di qualsiasi Contenuto, in qualsiasi forma, media, o tecnologia, sia attualmente conosciuto o successivamente sviluppato, da solo o come parte di altri lavori, oppure utilizzando la User Content all'interno o in connessione con i nostri prodotti o servizi. Inoltre, Lei ci concede il diritto di utilizzare il proprio nome, immagine e somiglianza per qualsiasi scopo, in qualsiasi modo che sia in linea con il suo Contenuto Utente.</p>
		<p>Tutti le terze parti, e non noi, sono interamente responsabili per i Contenuti che l’utente pubblica nell'Applicazione. L'utente accetta di non impegnarsi, assistere o incoraggiare altri nella  trasmissione, caricamento, pubblicazione, e-mail o altra forma diversa di Contenuti dell’Utente che  (a) siano illeciti, dannosi, minatori, abusivi, molesti, diffamatori, volgari, osceni, pornografici, diffamatori, lesivi della privacy altrui, odiosi, o razziali, etnici o altro, (b) non si ha il diritto di rendere disponibile ai sensi di legge o di rapporti contrattuali o fiduciari; c) <u>che sai essere falsi, inesatti o fuorvianti; (d) per cui hai ricevuto compenso o alcun corrispettivo da parte di terzi</u> (e) violazione di brevetti, marchi, segreti industriali, copyright o altri diritti di proprietà di terzi. Inoltre, Lei accetta di non trasmettere, caricare, pubblicare, e-mail o altrimenti rendere disponibile qualsiasi virus software, pubblicità non richiesta o non autorizzata, sollecitazione o materiale promozionale, tra cui catene di Sant'Antonio, mailing di massa, o qualsiasi forma di "spam". Lei accetta inoltre di non (i) impersonare altre persone o entità, dichiarare il falso o altrimenti travisare la propria affiliazione con una persona o entità, (ii) "perseguitare" o molestare <u>anche sostenendo le molestie di un altro</u>, intrappolare o danneggiare terzi, <u>compreso danneggiare i minori in qualsiasi modo</u>, (iii) creare intestazioni o in altro modo manipolare identificativi allo scopo di nascondere l'origine di qualsiasi Contenuto, (iv) intenzionalmente o non intenzionalmente violare qualsiasi legge locale, statale, nazionale o internazionale, o (v) raccogliere o memorizzare i dati personali di altri utenti.</p>
		<p>Noi non approviamo né controlliamo il Contenuto Utente trasmesso o postato riguardante l'applicazione e, pertanto, non è possibile garantire l'accuratezza, l'integrità o la qualità del Contenuto Utente. Lei è consapevole che utilizzando l'applicazione, potrebbe essere esposto a Contenuti per lei  offensivi, indecenti o discutibili. In nessun caso potremo essere ritenuti responsabili in alcun modo per i Contenuti dell'utente, compresi, senza limitazione, per eventuali errori o omissioni nei Contenuti dell'utente, o per qualsiasi perdita o danni di qualsiasi genere subiti dall'utente in conseguenza dell'uso di qualsiasi contenuti Utente trasmessi, caricati, inviati, via e-mail o in altro modo reso disponibile tramite l'applicazione.</p>

		<p>Non siamo in alcun modo responsabili dell'esaminazione o della valutazione dell’azione in cui Lei e il suo Cerchio di Forza avete accettato di impegnarsi, né siamo obbligati ad approvare la vostra azione o Cerchio di Forza. Non ci assumiamo alcuna responsabilità per la selezione o il completamento della vostra azione o per la mancata realizzazione dell’azione da voi o qualcuno nella vostra cerchia di Forza.<br/>
		Lei riconosce che noi abbiamo il diritto (ma non l'obbligo), a nostra esclusiva discrezione, di rifiutare di pubblicare o rimuovere qualsiasi Contenuto Utente e ci riserviamo il diritto di cambiare, condensare, o cancellare qualsiasi Contenuto Utente. Senza limitare la generalità di quanto sopra o di qualsiasi altra disposizione di questi Termini e Condizioni, noi abbiamo il diritto di rimuovere qualsiasi Contenuto che violi le presenti Condizioni Generali o in altro modo reprensibile e ci riserviamo il diritto di rifiutare il servizio senza preavviso, per tutti gli utenti che violano i presenti Termini e Condizioni o di violare i diritti degli altri.</p>

		<h3>7.  Reclami di Copyright</h3>
		<p>Rispettiamo la proprietà intellettuale di altri. Se crede che i materiali protetti da copyright siano stati copiati in un modo che costituisce violazione del copyright, la preghiamo di inviare una e-mail o comunicazione scritta al nostro agente designato per eventuali segnalazioni di violazione e di fornire le seguenti: (i) l'identificazione del lavoro protetto da copyright che si ritiene sia stato violato e la conferma che tu sei il proprietario del copyright o autorizzato ad agire per conto del proprietario del copyright, (ii) una descrizione del materiale che si sostiene violi e la posizione di tale materiale sul Sito, (iii) il suo  indirizzo, numero di telefono e indirizzo di posta elettronica.</p>
		<p><strong>Our Designated Agent for notice for claims of copyright infringement is Gregg Marrazzo, Senior Vice President and Deputy General Counsel, The Estée Lauder Companies Inc., 767 Fifth Avenue, New York, N.Y.  10153.  Telephone: (212) 277-2320.  Email: gmarrazz@estee.com.</strong></p>
		<p>NOTA: L’INDIRIZZO RIPORTATO SOPRA E’ FORNITO ESCLUSIVAMENTE PER LE NOTIFICHE RELATIVE AD AVEDA PER LE EVENTUALI VIOLAZIONI DI COPYRIGHT.  TUTTE LE ALTRE DOMANDE NON RICEVERANNO RISPOSTA ATTRAVERSO QUESTO PROCESO  E DOVREBBERO ESSERE DIRETTE AL NOSTRO SERVIZIO CLIENTI VIA EMAIL responsabileprivacy@it.estee.com</p>

		<h3>8. Dichiarazioni e garanzie; limitazioni di responsabilità</h3>
		<p>L’APPLICAZIONE E’ PRESENTATA "COME E’". NOI NON FACCIAMO ALCUNA DICHIARAZIONE O GARANZIA DI QUALSIASI TIPO, ESPLICITA O IMPLICITA, IN RELAZIONE A QUESTI TERMINI E CONDIZIONI O L’APPLICAZIONE, COMPRESO MA NON LIMITATO, LE GARANZIE DI COMMERCIABILITÀ, NON VIOLAZIONE O IDONEITÀ PER UN PARTICOLARE SCOPO, FATTA ECCEZIONE PER QUANTO TALI DICHIARAZIONI E GARANZIE NON SONO LEGALMENTE ESCLUDIBILI.</p>
		<p>LEI ACCETTA CHE, NELLA MISURA MASSIMA CONSENTITA DALLA LEGGE APPLICABILE, NON SAREMO RESPONSABILI (PER CONTRATTO, ILLECITO (INCLUSA LA NEGLIGENZA) O ALTRO), IN NESSUNA CIRCOSTANZA, PER DANNI (a), INTERRUZIONE DI LAVORO, (b) RITARDI DI ACCESSO O ACCESSO INTERROTTO DELL’APPLICAZIONE; (c) DATI NON CONSEGNATI, CONSEGNA ERRATA, CORRUZIONE, DISTRUZIONE, O ALTRA MODIFICA, (d) PERDITA O DANNI DI QUALSIASI DERIVANTI DA SITI ESTERNI DELL’APPLICAZIONE; (e) VIRUS INFORMATICI, ERRORI DI SISTEMA O MALFUNZIONAMENTI CHE POSSONO VERIFICARSI IN RELAZIONE ALL'USO DELL’APPLICAZIONE, SNCHE DURANTE IL COLLEGAMENTO IPERTESTUALE O DA APPLICAZIONI WEB DI TERZI (f) EVENTUALI INESATTEZZE O OMISSIONI DI CONTENUTI (g) EVENTI AL DI FUORI DEL NOSTRO CONTROLLO.</p>
		<p>INOLTRE, NEI LIMITI CONSENTITI DALLA LEGGE, NOI NON POTREMO ESSERE RITENUTI RESPONSABILI PER DANNI INDIRETTI, SPECIALI, MORALI, INCIDENTALI, O CONSEGUENTI DANNI DI QUALSIASI TIPO (INCLUSI PERDITA DI PROFITTI) INERENTI ALL'APPLICAZIONE O DAL SUO USO INDIPENDENTEMENTE DALLA FORMA DI AZIONE, ATTO ILLECITO (INCLUSA LA NEGLIGENZA) O ALTRIMENTI, ANCHE SE SIAMO STATI INFORMATI DELLA POSSIBILITA’ DI TALI DANNI E IN NESSUN CASO LA NOSTRA RESPONSABILITA’MASSIMA COMPLESSIVA PUO’ SUPERARE I CENTO DOLLARI</p>
		<p>LEI ACCETTA CHE NESSUN RECLAMO O AZIONE DERIVANTE, O CONNESSA A, L'UTILIZZO DELL’APPLICAZIONE O DEI TERMINI E CONDIZIONI POSSONO ESSERE UTILIZZATI DA LEI PER PIU’ DI UN (1) ANNO DAL VERIFICASI DI AZIONI RELATIVI A TALI RICHEISTE O AZIONI SORTE.</p>

		<h3>9. Indennizzo</h3>
		<p>Lei accetta di difendere, manlevare e tenere indenne per eventuali perdite, danni o spese, incluse le ragionevoli spese legali, derivanti da qualsiasi pretesa di terzi, l'azione o la domanda derivante dal tuo uso dell'Applicazione o violazione di questi Termini e Condizioni. Lei accetta inoltre di risarcire noi per eventuali perdite, danni o spese, incluse le ragionevoli spese legali, derivanti dall'uso di software robot, spider, crawler, o altri raccoglitori di dati simili e strumenti di estrazione, o di qualsiasi altra azione che si prende che imponga un onere irragionevole o eccessivo sulla nostra infrastruttura.</p>

		<h3>10. Controversie</h3>
		<p>In relazione a qualsiasi controversia relativa all’ Applicazione, tutti i diritti e gli obblighi e tutte le azioni previste dai presenti Termini e condizioni sono disciplinati dalle leggi di New York, come se i Termini e Condizioni fossero un contratto interamente sottoscritto e interamente eseguito all'interno di New York. Qualsiasi controversia relativa in alcun modo per la sua visita all’Applicazione sarà sottoposta ad arbitrato confidenziale a New York e si sottoporrà alla giurisdizione e procedimenti della stessa, salvo che, nella misura in cui si ha in qualsiasi modo violato o minacciato di violare la nostra proprietà di diritti intellettuali diritti o  ai diritti di proprietà intellettuale dei nostri affiliati, partner o licenzianti o hanno una causa di azione del patrimonio netto, possiamo cercare ingiuntivo o altra adeguata riparazione in qualsiasi tribunale della giurisdizione competente e si accetta la giurisdizione e la sede in qualsiasi tribunale per tale scopi. Arbitrato ai sensi del presente accordo deve essere condotta secondo le controversie legate ai consumi supplementari norme allora vigenti con l'American Arbitration Association. Il lodo arbitrale è vincolante e potrà essere esibito come sentenza in qualsiasi tribunale della giurisdizione competente. Nella misura massima consentita dalla legge applicabile, nessun arbitrato ai presenti Termini e Condizioni si unirà ad un arbitrato che coinvolga qualsiasi altra parte soggetta a questi Termini e Condizioni, sia per mezzo di una procedura di arbitrato di classe o altro</p>

		<h3>11. Generale</h3>
		<p>Lei dichiara di essere a conoscenza e accettare che i presenti Termini e condizioni costituiscono l'accordo completo ed esclusivo tra di noi riguardo il suo uso dell'Applicazione, e sostituiscono e governare tutte le proposte precedenti, accordi o altre comunicazioni.</p>
		<p>Ci riserviamo il diritto, a nostra esclusiva discrezione, di cambiare questi Termini e Condizioni in qualsiasi momento pubblicando le modifiche della domanda e avviso di tale cambiamento. Tutte le modifiche sono immediatamente effettive dopo l'applicazione e il rilascio di avviso di tale cambiamento. L'utilizzo continuato dell'Applicazione da allora in poi costituisce accettazione di tutti tali mutate Termini e Condizioni. Possiamo, con o senza preavviso, sospendere alcuni dei diritti concessi da questi Termini e Condizioni. Si ottempera immediatamente la risoluzione o altro avviso, tra cui, a seconda dei casi, cessando ogni utilizzo dell'Applicazione.</p>
		<p>Nulla di quanto contenuto nelle presenti Condizioni può essere interpretata come la creazione di qualsiasi agenzia, partnership, o altra forma di società mista tra noi. La nostra incapacità di richiedere le prestazioni di qualsiasi disposizione del presente Contratto non pregiudica il nostro pieno diritto di richiedere tale esecuzione in qualsiasi momento successivo, né la nostra rinuncia a una violazione di una disposizione del presente Contratto viene assunto o ritenuta una rinuncia alla clausola stessa. Nel caso in cui qualsiasi disposizione di questi Termini e Condizioni sarà inapplicabile o non valida ai sensi della legge applicabile o di essere così detenute da qualsiasi decisione arbitrale applicabile o decisione giudiziaria, tale inapplicabilità o invalidità non renda questi Termini e Condizioni inapplicabile o non valida nel suo insieme ma queste condizioni sono modificate, per quanto possibile, l'ente aggiudicatore per riflettere più pienamente l'intento originale delle parti, come previsto nella clausola originale.</p>
		<p>Per Qualsiasi domanda relative ai Termini e Condizioni, la preghiamo di scrivere al seguente indirizzo:  responsabileprivacy@it.estee.com</p>

	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>