<div class="popup" id="popup_legal">	
	<div id="popup_legal_content">
		<h2>CHIẾN DỊCH BCA 2013: ĐIỀU KHOẢN VÀ ĐIỀU KIỆN QUỐC TẾ</h2>
		<h3>Ngày có hiệu lực: 01/8/2013</h3>

		<p><strong>Chào mừng đến với Ứng dụng Facebook: Chiến dịch Nhận thức về Ung thư vú của công ty Estee Lauder (“Ứng dụng”)</strong></p>
		<p>Công ty Estee Lauder cung cấp nội dung và dịch vụ có sẵn trên Ứng dụng cho bạn theo các điều khoản và điều kiện dưới đây; Chính sách bảo mật, các điều khoản, điều kiện và các chính sách khác mà bạn có thể tìm thấy khi truy cập vào ứng dụng với các chức năng, tính năng hoặc các chương trình khuyến mãi cũng như dịch vụ khách hàng được coi là một phần và bao gồm trong các điều khoản và điều kiện này (được gọi chung là “Điều khoản và điều kiện”). Khi truy cập và sử dụng Ứng dụng, bạn công nhận rằng bạn đã đọc, hiểu và đồng ý mà không bị giới hạn năng lực hành vi dân sự nào, và bị ràng buộc bởi các điều khoản và điều kiện sau.</p>

		<h3>1. Bảo mật</h3>
		<p>Vui lòng xem Chính sách bảo mật để hiểu rõ về thủ tục bảo mật của chúng tôi.</p>

		<h3>2. Sở hữu trí tuệ</h3>
		<p>Ngoại trừ bất kì thông tin và/hoặc nội dung nào được cung cấp bởi công ty Facebook,trên cơ sở tôn trọng nền tảng của Facebook, tất cả các thông tin và nội dung khác có sẵn trên Ứng dụng và giao diện đối với người dùng của nó, bao gồm nhưng không giới hạn với các nhãn hiệu, logo, dấu hiệu dịch vụ, văn bản, đồ họa, biểu tượng dạng nút, hình ảnh, âm thanh, số liệu tổng hợp, phần mềm cũng như việc biên soạn và sắp xếp chúng (gọi chung là “nội dung”) đều là tài sản của công ty Estee Lauder, các công ty thành viên, đối tác hoặc người cấp phép của chúng tôi, và được bảo hộ bởi luật pháp Mỹ và luật pháp quốc tế, bao gồm các điều luật quy định quyền tác giả và nhãn hiệu.</p>
		<p>Ngoại trừ những điều đã nêu trong giấy phép giới hạn tại Phần 3, hoặc được yêu cầu bởi luật áp dụng, không có bất kì Nội dung hoặc phần nào của Ứng dụng được phép tái sử dụng, nhân đôi, sao chép, bán, bán lại , truy cập, sửa chữa, hoặc khai khác, tất cả hoặc từng phần, với bất kì mục đích nào mà không được sự cho phép trước của chúng tôi bằng văn bản.</p>

		<h3>3. Cấp phép giới hạn</h3>
		<p>Quyền truy cập và sử dụng Ứng dụng của bạn mang tính giới hạn, có thể bị hủy bỏ và không dành riêng cho bất cứ ai. Cấp phép giới hạn này không bao gồm các quyền: (a) sửa đổi hoặc sử dụng kĩ thuật chỉnh sửa để đính kèm Ứng dụng hoặc bất cứ phần nào trong đó; (b) tái bản, phân phối lại, truyền phát, bán, cấp phép hoặc tải về Ứng dụng hoặc bất cứ nội dung nào (ngoại trừ phần được lưu trong bộ nhớ đệm hoặc nếu thấy cần thiết để xem được Ứng dụng); (c) sử dụng bất cứ phần Nội dung nào của Ứng dụng ngoài mục đích cá nhân; (d) sử đổi, đảo ngược thiết kế hoặc tạo ra các hoạt động phát sinh dựa trên Ứng dụng hoặc bất cứ phần Nội dung nào của nó; (e) thu thập thông tin tài khoản vì lợi ích của bản thân hoặc cho một bên khác; (f) dùng thẻ meta và các “đoạn mã ẩn” khác sử dụng Nội dung của ứng dụng; hoặc (g) sử dụng robot phần mềm, spider, các chương trình thu thập hoặc các phương tiện khai thác, tập hợp dữ liệu tương đương, hoặc có các hành động khác có thể làm quá tải hệ thống của chúng tôi. Bạn phải giữ nguyên, không được thay đổi các thông tin độc quyền được liên kết hoặc bao gồm trong Ứng dụng này.</p>
		<p>Cấp phép giới hạn được nêu trong phần 3 sẽ tự động chấm dứt nếu bạn có hành vi sử dụng trái phép Ứng dụng cũng như toàn bộ hay bất kì phần nội dung nào trong đó mà không phương hại đến các biện pháp khác có trong luật áp dụng hoặc các điều được nêu trong bản Điều khoản và điều kiện này.</p>

		<h3>4. Nghĩa vụ và trách nhiệm của bạn</h4>
		<p>Khi truy cập hoặc sử dụng Ứng dụng, bạn tuân thủ các điều khoản và điều kiện, các khuyến cáo đặc biệt hoăc hướng dẫn để truy cập hoặc sử dụng được đăng lên Ứng dụng. Bạn có trách nhiệm hành động phù hợp với luật pháp, phong tục và đạo đức. Bạn không được thay đổi hoặc sửa chữa bất kì nội dung hay dịch vụ nào có trong Ứng dụng và không làm hư hỏng bằng bất kì cách nào hoạt động của Ứng dụng. Không hạn chế các quy tắc chung của các điều khác trong bản Điều khoản và điều kiện, nếu bạn vô ý hoặc cố ý trong bất kì nghĩa vụ nào đã được quy định trong bản Điều khoản và điều kiện này, bạn phải chịu trách nhiệm về tất cả những tổn thất và thiệt hại đã gây ra cho công ty Estee Lauder, các công ty thành viên, đối tác và người cấp phép của chúng tôi.</p>

		<h3>5. Liên hệ với bên thứ ba</h3>
		<p>Chúng tôi không chịu trách nhiệm về nội dung của bất kì trang nào ngoài trang web và các trang web khác từ hoặc liên kết với Ứng dụng. Các liên kết xuất hiện trong Ứng dụng chỉ phục vụ cho sự tiện lợi mà không được chúng tôi cũng như các công ty thành viên và đối tác của chúng tôi chứng thực về nội dung tham khảo, sản phẩm, dịch vụ và nguồn cung cấp. Bạn chấp nhận rủi ro khi truy cập vào các trang ngoài trang web của chúng tôi. Chúng tôi không chịu trách nhiệm về việc giám định hay đánh giá, và chúng tôi không đảm bảo dịch vụ của các trang ngoài trang web và các trang web khác liên kết đến hoặc từ Ứng dụng; chúng tôi cũng không chịu trách nhiệm hoặc nghĩa vụ pháp lí đối với các hành động, nội dung, sản phẩm hay dịch vụ của các trang và trang web vừa nêu, bao gồm (mà không có giới hạn) cả chính sách bảo mật, điều kiện và điều khoản của họ. Bạn cần phải xem xét cẩn thận các điều khoản và các trang web ngoài website của Estee Lauder mà bạn truy cập.</p>

		<h3>6. Nội dung người dùng</h3>
		<p>Khi bạn truy cập, tải lên, đăng, gửi email hoặc tạo ra các dữ liệu, phần mềm, nhạc, âm thanh, hình ảnh, đồ họa, video, tin nhắn hoặc các tài liệu khác (Nội dung người dùng) tại Ứng dụng, bạn hoàn toàn chịu trách nhiệm với các nội dung đó. Chính sách của chúng tôi từ chối chấp nhận những lời đề nghị hoặc ý tưởng tự nguyện. Tuy nhiên, những lời đề nghị và ý kiến tự nguyên, thắc mắc, hồi đáp hoặc những thông tin khác mà bạn cung cấp (gọi chung là Bản đệ trình) không được coi là tài sản của bạn và không được giữ bí mật. Bạn công nhận rằng Bản đệ trình sẽ không được hoàn trả và chúng tôi có thể sử dụng bất kì ý tưởng, khái niệm hoặc kiến thức nào trong Bản đệ trình mà không cần thanh toán bằng tiền hay bất kì một hình thức trả công nào khác, phục vụ cho mọi mục đích bao gồm phát triển, sản xuất, phân phối và quảng bá sản phẩm mà không bị giới hạn. Bản đệ trình được xem là một phần của Nội dung người dùng.</p>
		<p>Theo các điều khoản trong Chính sách bảo mật của chúng tôi, khi bạn gửi hoặc đăng bất kì Nội dung người dùng nào lên Ứng dụng, chúng tôi có quyền được chuyển nhượng, không độc quyền, tạo hợp đồng thứ cấp, miễn trả tiền bản quyền trong việc sao chép, sử dụng, mô phỏng, sửa đổi, chỉnh sửa, dịch, xuất bản, phân phối, bán hoặc chuyển nhượng Nội dung người dùng đó bằng bất cứ phương pháp nào chúng tôi thấy hợp lý, bao gồm (nhưng không giới hạn) quyền được được sao chép tất cả hay từng phần, tạo ra các sản phẩm phát sinh, phân phối hoặc trưng bày nội dung này dưới bất kì hình thức, phương tiện truyền thông hoặc kĩ thuật, bất kể trong hiện tại hay sẽ được phát triển trong tương lai, riêng lẻ hay là một phần của công trình khác, hoặc sử dụng Nội dung người dùng trong hoặc liên quan đến sản phẩm và dịch vụ của chúng tôi. Thêm vào đó, bạn cung cấp cho chúng tôi quyền được sử dụng tên, hình ảnh, chân dung của bạn trong bất kì mục đích nào mà chúng tôi thấy phù hợp với Nội dung người dùng của bạn.</p>
		<p>Tất cả bên thứ ba phải chịu trách nhiệm về Nội dung và họ đăng lên Ứng dụng. Bạn đồng ý không tham gia, hỗ trợ hoặc khuyến khích các thành viên khác truyền tải, tải lên, đăng, email hoặc tạo ra các nội dung mà (a) vi phạm pháp luật, độc hại, đe dọa, sỉ nhục, quấy nhiễu, phỉ báng, thô tục, khiêu dâm, bôi nhọ, xâm phạm riêng tư của người khác, hận thù, phân biệt chủng tộc, dân tộc và các hành động gây khó chịu khác; (b) bạn không có quyền tạo ra dưới bất kì luật hay hợp đồng hoặc sự ủy thác nào; (c) bạn biết là sai trái, không chính xác hoặc dễ gây hiểu lầm; (d) bạn đã được bồi thường hoặc được thưởng bởi bất kì bên thứ ba nào; (e) vi phạm bất cứ bằng sáng chế, thương hiệu, bí mật thương mại, bản quyền hoặc quyền sở hữu của bất kì bên nào. Ngoài ra, bạn đồng ý không truyền tải, tải lên, đăng, email hoặc tạo ra bất kì loại virus phần mềm, các khuyến mãi trái phép, cái tài liệu quảng cáo chèo kéo khách hàng bao gồm thư hàng loạt, thư dây chuyền hoặc các loại “thư rác” khác. Bạn còn đồng ý không (i) mạo danh bất kì người nào hay tổ chức nào, hoặc xuyên tạc hay trình bày sai về bất cứ cá nhân hay tổ chức nào khác; (ii) “theo dõi” hay quấy rối bao gồm vận động quấy rối người khác, lừa dối hoặc phương hại đến bên thứ ba, bao gồm trẻ vị thành niên bằng bất kì cách nào; (iii) giả mạo tiêu đề hoặc giả mạo danh tính để ngụy trang Nội dung người dùng gốc; (iv) vô tình hay cố ý vi phạm luật áp dụng địa phương, bang, quốc gia và quốc tế; hoặc (v) thu thập và lưu trữ số liệu nhận dạng cá nhân của những người dùng khác.</p>
		<p>Chúng tôi không chứng thực hay kiểm soát những nội dung mà người truyền tải hoặc đăng lên Ứng dụng và do đó, chúng tôi không đảm bảo tính chính xác, tính toàn vẹn và chất lượng của các nội dung này. Bạn hiểu rằng, khi sử dụng Ứng dụng, bạn có thể tiếp xúc với các thông tin công kích, bất lịch sự hoặc gây khó chịu. Trong mọi trường hợp, chúng tôi không chịu trách nhiệm pháp lý về bất cứ Nội dung người dùng nào, bao gồm (không giới hạn), với bất kì lỗi hoặc thiếu sót trong phần Nội dung này, hoặc bất kì mất mát hay tổn hại dưới bất kì hình thức nào bạn phải chịu mà đó là kết quả của việc truyền tải, tải lên, đăng, email hoặc tạo ra bất cứ Nội dung người dùng nào bằng Ứng dụng.</p>
		<p>Chúng tôi không chịu trách nhiệm cho việc giám định hoặc đánh giá các hoạt động của chương trình Hành động mà trong đó bạn và tổ chức Circle of Strength đã đồng ý tham gia, chúng tôi cũng không có nghĩa vụ phải tán thành chương trình Hành động hoặc Circle of Strength. Chúng tôi không chịu bất kì trách nhiệm hay nghĩa vụ pháp lý nào về việc lựa chọn hoặc hoàn thành chương trình Hành động hoặc sự thất bại của chương trình bởi bạn hay bất kì ai tham gia Circle of Strength.</p>
		<p>Bạn công nhận rằng chúng tôi có quyền (nhưng không có bổn phận) từ chối đăng hoặc xóa bỏ bất kì Nội dung người dùng nào theo quyết định của mình, và chúng tôi có quyền thay đổi, rút gọn, hoặc xóa bỏ bất cứ Nội dung người dùng nào. Không giới hạn quy tắc chung của bất cứ điều khoản nào đã được đề cập trong phần Điều khoản và điều kiện, chúng tôi có quyền gỡ bỏ tất cả những Nội dung người dùng nào bị phản đối hoặc vi phạm nội dung của bản Điều khoản và điều kiện này. Chúng tôi cũng có quyền từ chối cung cấp dịch vụ mà không cần báo trước cho những người dùng nào đã vi phạm phần nội dung nói trên hoặc xâm phạm quyền của người khác.</p>

		<h3>7. Khiếu nại bản quyền</h3>
		<p>Chúng tôi tôn trọng quyền sở hữu trí tuệ của người khác. Nếu bạn tin rằng các tài liệu có bản quyền đã bị sao chép mà có thể cấu thành tội vi phạm bản quyền, xin vui lòng gửi email hoặc thông báo bằng văn bản đến cho Bộ phận chuyên trách của chúng tôi để thông báo vi phạm và cung cấp các tài liệu sau: (i) giấy tờ chứng minh của công trình có bản quyền mà bạn cho rằng đã bị vi phạm và giấy xác nhận rằng bạn là người sở hữu tài sản trí tuệ hoặc có quyền đại diện cho chủ sở hữu bản quyền; (ii) bản mô tả tài liệu mà bạn cho rằng đã bị vi phạm và vị trí của tài liệu đó trên trang web; (iii) địa chỉ, số điện thoại và địa chỉ email của bạn.</p>
		<p><strong>OBộ phận chuyên trách của chúng tôi để thông báo về vi phạm bản quyền là: Gregg Marrazzo, Senior Vice President and Deputy General Counsel, The Estée Lauder Companies Inc., 767 Fifth Avenue, New York, N.Y.  10153. Số điện thoại: (212) 277-2320. Email: gmarrazz@estee.com.</strong></p>
		<p>CHÚ Ý: THÔNG TIN LIÊN LẠC ĐƯỢC CUNG CẤP Ở TRÊN CHỈ DÀNH CHO VIỆC THÔNG BÁO VI PHẠM BẢN QUYỀN. TẤT CẢ CÁC THẮC MẮC KHÁC SẼ KHÔNG NHẬN ĐƯỢC PHẢN HỒI VÀ ĐƯỢC CHUYỂN ĐẾN BỘ PHẬN CHĂM SÓC KHÁCH HÀNG CỦA CHÚNG TÔI BẰNG CÁCH EMAIL ĐẾN consumercare-us@gcc.elc.estee.com.</p>

		<h3>8. Đại diện và Bảo đảm; Giới hạn Trách nhiệm</h3>
		<p>ỨNG DỤNG ĐƯỢC GIỮ “NGUYÊN TRẠNG". CHÚNG TÔI KHÔNG ĐẠI DIỆN HOẶC BẢO ĐẢM BẤT CỨ ĐIẾU GÌ, TRỰC TIẾP HAY GIÁN TIẾP, LIÊN QUAN ĐẾN CÁC ĐIỀU KHOẢN VÀ ĐIỀU KIỆN HOẶC ỨNG DỤNG, BAO GỒM NHƯNG KHÔNG GIỚI HẠN ĐẾN VIỆC  BẢO ĐẢM THƯƠNG MẠI, KHÔNG XÂM PHẠM HAY PHÙ HỢP CHO MỘT MỤC ĐÍCH CỤ THỂ, NGOẠI TRỪ PHẠM VI CỦA CÁC ĐẠI DIỆN VÀ ĐẢM BẢO TRÊN LÀ KHÔNG MIỂN TRỪ TRÁCH NHIỆM PHÁP LÝ.</p>
		<p>BẠN ĐỒNG Ý RẰNG, TRONG PHẠM VI PHÁP LUẬT CHO PHÉP HIỆN HÀNH, CHÚNG TÔI SẼ KHÔNG CHỊU TRÁCH NHIỆM HOẶC NGHĨA VỤ PHÁP LÝ (CHO DÙ ĐƯỢC ĐỂ CẬP TRONG HỢP ĐỒNG HAY KHÔNG, DO SAI LẦM (BAO GỒM SƠ SUẤT) HOẶC TRONG TRƯỜNG HỢP KHÁC), TRONG BẤT CỨ TÌNH HUỐNG (a) GIÁN ĐOẠN KINH DOANH, (b) TRUY CẬP BỊ CHẬM TRỄ  HOẶC GIÁN ĐOẠN (c) DỮ LIỆU KHÔNG CHUYỂN ĐƯỢC, CHUYỂN NHẦM, SỬA ĐỔI, TIÊU HỦY, HOẶC CÁC ĐIỀU CHỈNH KHÁC (d) CÁC LOẠI MẤT HAY HƯ HỎNG LÀ KẾT QUẢ CỦA VIỆC XỬ LÝ HOẶC HIỆN DIỆN CỦA CÁC LIÊN KẾT ỨNG DỤNG KHÔNG LIÊN QUAN ĐẾN MẠNG INTERNET (e) VI-RÚT MÁY TÍNH, LỖI HỆ THỐNG HOẶC SỰ CỐ CÓ THỂ XẢY RA LIÊN QUAN ĐẾN VIỆC SỬ DỤNG ỨNG DỤNG, KỂ CẢ TRONG CÁC LIÊN KẾT ĐẾN HOẶC TỪ CÁC ỨNG DỤNG TỪ TRANG WEB CỦA BÊN THỨ BA (f) BẤT KỲ VIỆC THIẾU CHÍNH XÁC HOẶC THIẾU SÓT TRONG NỘI DUNG HOẶC (g) SỰ KIỆN VƯỢT QUÁ TẦM KIỂM SOÁT CỦA CHÚNG TÔI.</p>
		<p>HƠN NỮA, TRONG PHẠM VI PHÁP LUẬT CHO PHÉP, CHÚNG TÔI SẼ KHÔNG CHỊU TRÁCH NHIỆM CHO BẤT CỨ THIỆT HẠI GIÁN TIẾP, ĐẶC BIỆT, NGẪU NHIÊN HOẶC THIỆT HẠI DO  CHỦ QUAN  (BAO GỒM TỔN THẤT LỢI NHUẬN) LIÊN QUAN ĐẾN CÁC ỨNG DỤNG HAY VIỆC SỬ DỤNG CỦA BẠN DƯỚI BẤT KỲ HÌNH THỨC NÀO DÙ CÓ ĐỂ CẬP TRONG HỢP ĐỒNG HAY KHÔNG, DO SAI LẦM (BAO GỒM SƠ SUẤT) HOẶC TRONG MỌI TRƯỜNG HỢP KHÁC, NGAY CẢ KHI CHÚNG TÔI ĐÃ ĐƯỢC KHUYẾN CÁO VỀ KHẢ NĂNG XẢY RA CÁC THIỆT HẠI NÀY VÀ KHÔNG CÓ BẤT CỨ  TRƯỜNG HỢP NÀO TỔNG TRÁCH NHIỆM TỐI ĐA CỦA CHÚNG TÔI VƯỢT QUÁ MỘT TRĂM ĐÔ LA ($ 100.00).</p>
		<p>BẠN ĐỒNG Ý RẰNG SẼ KHÔNG ĐƯA RA CÁC KHIẾU NẠI HOẶC KHIẾU KIỆN LIÊN QUAN ĐẾN VIỆC SỬ DỤNG ỨNG DỤNG HAY NHỮNG ĐIỀU KHOẢN VÀ ĐIÊU KIỆN NÀY HƠN MỘT (1) NĂM SAU KHI NGUYÊN NHÂN LIÊN QUAN ĐẾN KHIẾU NẠI HAY KHIẾU KIỆN PHÁT SINH.</p>

		<h3>9. Sự bồi thường</h3>
		<p>Bạn đồng ý bảo vệ, bồi thường và đảm bảo rằng chúng tôi sẽ không bị bất cứ thiệt hại nào liên quan đến việc tổn thất, thiệt hại hay chi phí, bao gồm cả phí luật sư hợp lý, phát sinh do bất kỳ khiếu nại, hành động của bên thứ ba, hoặc do việc sử dụng các ứng dụng hoặc vi phạm các Điều khoản và Điều kiện này. Bạn cũng đồng ý bồi thường cho chúng tôi bất kỳ tổn thất, thiệt hại, hay chi phí, bao gồm cả phí luật sư hợp lý, từ việc sử dụng các phần mềm robots, spiders, crawlers hoặc các công cụ thu thập, hoặc lấy dữ liệu, hoặc bất kỳ hành động nào làm chiếm dung lượng đường truyền của chúng tôi.</p>

		<h3>10. Tranh chấp</h3>
		<p>Bằng sự tôn trọng đối với bất kỳ tranh chấp liên quan đến ứng dụng, tất cả các quyền và nghĩa vụ và tất cả các hành động dự kiến trong Các Điều khoản và Điều kiện này sẽ được điều chỉnh bởi luật pháp của New York, như thể các Điều khoản và Điều kiện là một hợp đồng hoàn toàn được ký kết và thực hiện ở New York. Trong mọi trường hợp, mọi tranh chấp liên quan đến việc truy cập vào ứng dụng sẽ được đưa ra trọng tài bí mật ở New York và bạn phải tuân theo sự xét xử và thủ tục tố tụng của tòa án này, ngoại trừ việc, trong các trường hợp bạn vi phạm hoặc đe dọa vi phạm sở hữu trí tuệ của chúng tôi hoặc quyền sở hữu trí tuệ của các chi nhánh của chúng tôi, các đối tác hoặc người cấp phép, hoặc có nguyên nhân tố tụng theo luật công lý, chúng tôi có thể tìm kiếm lệnh bồi thường hay trợ giúp thích hợp khác, ở bất kỳ tòa án có thẩm quyền và bạn đồng ý với thẩm quyền và địa điểm trong bất kỳ tòa án như vậy cho mục đích như vậy. Việc xét xử theo thỏa thuận này sẽ được tiến hành theo luật tranh chấp liên quan đến người tiêu dùng bổ sung và hiện hành và thông báo đến Hiệp hội Trọng tài Mỹ. Sự quyết định của trọng tài sẽ được áp dụng và có thể xem như một bản án trong bất kỳ tòa án có thẩm quyền nào. Trong phạm vi pháp luật cho phép hiện hành, việc phân xử dựa vào Điều khoản và Điều kiện này sẽ không áp dụng cho việc phân xử  liên quan đến bất kỳ bên nào khác, dù cho có thông qua thủ tục tố tụng trọng tài cao cấp hay không.</p>

		<h3>11. Qui định chung</h3>
		<p>Bạn thừa nhận và đồng ý rằng các Điều khoản và Điều kiện này là thỏa thuận hoàn chỉnh và duy nhất giữa chúng tôi liên quan đến việc bạn sử dụng các ứng dụng, thay thế và chi phối tất cả các đề xuất, thỏa thuận, hoặc các thông báo khác trước đây.</p>
		<p>Chúng tôi có quyền, tùy theo quyết định của chúng tôi, thay đổi các Điều khoản và Điều kiện bất cứ lúc nào bằng cách đăng những thay đổi trên ứng dụng và thông báo về sự thay đổi đó. Bất kỳ thay đổi nào cũng có hiệu lực ngay lập tức khi được đăng lên ứng dụng và phát hành thông báo về sự thay đổi đó. Khi tiếp tục sử dụng các ứng dụng là bạn chấp nhận các thay đổi của các Điều khoản và Điều kiện. Chúng tôi có thể có hoặc không có thông báo trước, chấm dứt bất kỳ các quyền được cấp bởi các Điều khoản và Điều kiện. Bạn phải thực hiện việc chấm dứt hoặc thực hiện theo thông báo khác ngay lập tức, nếu có, bằng cách chấm dứt sử dụng ứng dụng.</p>
		<p>Không có nội dung nào trong các Điều khoản và Điều kiện được hiểu như tạo ra bất kỳ sự môi giới, quan hệ đối tác, hoặc các hình thức doanh nghiệp liên doanh với chúng tôi. Việc không yêu cầu bạn thực hiện bất kỳ điều khoản về chính sách này  không ảnh hưởng đến việc chúng tôi có toàn quyền để yêu cầu bạn thực hiện tại bất cứ thời điểm nào sau đó, cũng như việc chúng tôi không bỏ qua sự vi phạm bất kỳ điều khoản nào trong chính sách này được thực hiện một cách cố ý. Trong trường hợp các quy định của Điều khoản và Điều kiện này không thể thi hành hoặc vô hiệu theo luật pháp hiện hành hoặc bởi bất kỳ phán quyết có hiệu lực của trọng tài hoặc quyết định của tòa án, việc không thể thi hành hoặc vô hiệu này sẽ không làm cho toàn bộ Điều khoản và Điều kiện không thể thi hành hoặc vô hiệu, mà Điều khoản và Điều kiện này sẽ được sửa đổi, đến mức có thể, bởi các đơn vị xét xử để phản ánh đầy đủ nhất so với dự định ban đầu của các bên như được phản ánh trong điều khoản cũ.</p>
		<p>Nếu bạn có bất kỳ câu hỏi liên quan đến các điều khoản và điều kiện, hãy gửi email cho chúng tôi tại consumercare-us@gcc.elc.estee.com.</p>

	</div>
</div>
<script type="text/javascript">
	$('#popup_legal_content').jScrollPane({hideFocus:true, mouseWheelSpeed:3});
	var api = $('#popup_legal_content').data('jsp');
	var throttleTimeout;
	$('html').addClass('_resize_');
	$(window).bind(
		'resize',
		function()
		{
			if ($('html').hasClass('lt-ie9')) {
				if (!throttleTimeout) {
					throttleTimeout = setTimeout(
						function()
						{
							api.reinitialise();
							throttleTimeout = null;
						},
						50
					);
				}
			} else {
				api.reinitialise();
			}
		}
	);
</script>